import XCTest
@testable import SiliconBuddy

/// The mirrored types, checked against the Mac's own export.
///
/// `contract/` is generated by silicon-optimizer's `ContractExportTests` — the shapes
/// its wire types actually encode, not something written by hand here. Each file holds
/// a route: its request, its response, the events it can send and the errors it can
/// answer. The round trip is the part that matters: decode, re-encode, compare the
/// JSON. A field this app forgot to mirror disappears in the re-encode, so the
/// comparison fails — which is the drift that would otherwise be discovered by a
/// person staring at a blank row.
final class ContractTests: XCTestCase {

    // MARK: - Fixtures

    private func fixture(_ name: String) throws -> [String: JSONValue] {
        let bundle = Bundle(for: ContractTests.self)
        let url = try XCTUnwrap(
            bundle.url(forResource: name, withExtension: "json", subdirectory: "contract")
                ?? bundle.url(forResource: name, withExtension: "json"),
            "Missing fixture \(name).json — run contract/refresh.sh"
        )
        let value = try JSONValue(data: try Data(contentsOf: url))
        guard case .object(let fields) = value else {
            throw XCTSkip("\(name).json is not a route fixture")
        }
        return fields
    }

    /// Decodes one part of a fixture — `response`, `request`, or one named event — then
    /// re-encodes it and compares field by field.
    @discardableResult
    private func roundTrip<T: Codable & Equatable>(
        _ type: T.Type, _ name: String, _ part: String = "response",
        file: StaticString = #filePath, line: UInt = #line
    ) throws -> T {
        let fields = try fixture(name)
        let piece: JSONValue
        if part.hasPrefix("events.") {
            let event = String(part.dropFirst("events.".count))
            piece = try XCTUnwrap(
                fields["events"]?[event], "\(name) has no \(part)", file: file, line: line
            )
        } else if part.hasPrefix("errors.") {
            let status = String(part.dropFirst("errors.".count))
            piece = try XCTUnwrap(
                fields["errors"]?[status], "\(name) has no \(part)", file: file, line: line
            )
        } else {
            piece = try XCTUnwrap(fields[part], "\(name) has no \(part)", file: file, line: line)
        }

        let data = try JSONEncoder().encode(piece)
        let decoded: T
        do {
            decoded = try JSONDecoder.buddy.decode(type, from: data)
        } catch {
            XCTFail("\(name).\(part) does not decode as \(type): \(error)", file: file, line: line)
            throw error
        }
        let reencoded = try JSONEncoder.buddy.encode(decoded)
        XCTAssertEqual(
            decoded, try JSONDecoder.buddy.decode(type, from: reencoded),
            "\(name).\(part) changed shape on a round trip", file: file, line: line
        )

        let original = piece.strippingNulls()
        let rebuilt = try JSONValue(data: reencoded).strippingNulls()
        if original != rebuilt {
            XCTFail(
                "\(name).\(part) lost or changed fields on a round trip:\n"
                    + original.difference(from: rebuilt).joined(separator: "\n"),
                file: file, line: line
            )
        }
        return decoded
    }

    // MARK: - The routes this app calls today

    func testHealth() throws {
        XCTAssertEqual(try roundTrip(ControlAPI.Health.self, "GET__health").status, "ok")
    }

    func testStatus() throws {
        let status = try roundTrip(ControlAPI.Status.self, "GET__status")
        XCTAssertTrue(status.hasLoadedModel)
    }

    func testProfile() throws {
        let profile = try roundTrip(ControlAPI.Profile.self, "GET__profile")
        XCTAssertFalse(profile.chip.isEmpty)
        XCTAssertGreaterThan(profile.totalMemoryBytes, 0)
    }

    func testMetrics() throws {
        let metrics = try roundTrip(ControlAPI.Metrics.self, "GET__metrics")
        XCTAssertGreaterThan(metrics.memoryTotalBytes, 0)
    }

    func testInstalled() throws {
        XCTAssertFalse(try roundTrip([ControlAPI.InstalledModel].self, "GET__installed").isEmpty)
    }

    func testCatalog() throws {
        let catalog = try roundTrip([ControlAPI.CatalogModel].self, "GET__catalog")
        XCTAssertTrue(catalog.contains { $0.recommendation != nil })
    }

    func testRecommend() throws {
        try roundTrip(ControlAPI.CatalogModel.self, "GET__recommend")
    }

    func testSwarm() throws {
        try roundTrip(ControlAPI.SwarmView.self, "GET__swarm")
    }

    func testNodeAdvertisement() throws {
        let node = try roundTrip(ControlAPI.NodeAdvertisement.self, "GET__v1_node")
        XCTAssertGreaterThan(node.profile.memoryGB, 0, "snake_case keys must map")
    }

    func testVideoModels() throws {
        try roundTrip([ControlAPI.VideoModel].self, "GET__video_models")
    }

    func testVideoQueue() throws {
        try roundTrip(ControlAPI.VideoQueueView.self, "GET__video_queue")
    }

    func testImageModels() throws {
        try roundTrip([ControlAPI.ImageModel].self, "GET__image_models")
    }

    func testMeshModels() throws {
        try roundTrip([ControlAPI.MeshModel].self, "GET__mesh_models")
    }

    func testChat() throws {
        try roundTrip(ControlAPI.ChatRequest.self, "POST__chat", "request")
        XCTAssertFalse(try roundTrip(ControlAPI.ChatResponse.self, "POST__chat").content.isEmpty)
    }

    func testLoadAndInstall() throws {
        try roundTrip(ControlAPI.LoadRequest.self, "POST__load", "request")
        try roundTrip(ControlAPI.Status.self, "POST__load")
        try roundTrip(ControlAPI.LoadRequest.self, "POST__install", "request")
        try roundTrip(ControlAPI.StatusMessage.self, "POST__install")
        try roundTrip(ControlAPI.StatusMessage.self, "POST__unload")
    }

    func testPlanRequest() throws {
        try roundTrip(ControlAPI.PlanRequest.self, "POST__plan", "request")
        try roundTrip(ControlAPI.Plan.self, "POST__plan")
    }

    // MARK: - The M0 routes

    func testPairing() throws {
        try roundTrip(BuddyAPI.PairRequest.self, "POST__buddy_pair", "request")
        let paired = try roundTrip(BuddyAPI.PairResponse.self, "POST__buddy_pair")
        XCTAssertEqual(BuddyAPI.DeviceScope(wire: paired.scope), .full)
        XCTAssertFalse(paired.token.isEmpty)
    }

    func testPairedDevices() throws {
        let devices = try roundTrip([BuddyAPI.PairedDevice].self, "GET__buddy_devices")
        XCTAssertEqual(devices.first?.scope, "full")
        try roundTrip(ControlAPI.StatusMessage.self, "DELETE__buddy_devices__id_")
    }

    func testConversations() throws {
        let summaries = try roundTrip([BuddyAPI.ConversationSummary].self, "GET__conversations")
        XCTAssertEqual(summaries.first?.messageCount, 2)
        try roundTrip(BuddyAPI.NewConversation.self, "POST__conversations", "request")
        try roundTrip(BuddyAPI.ConversationSummary.self, "POST__conversations")
    }

    func testConversationDetail() throws {
        let detail = try roundTrip(BuddyAPI.ConversationDetail.self, "GET__conversations__id_")
        XCTAssertFalse(detail.isGenerating)
        XCTAssertEqual(detail.messages.count, 2)
    }

    /// The route this app got wrong once: it takes one message, not a transcript.
    func testSendingAMessageToAConversation() throws {
        let request = try roundTrip(
            BuddyAPI.NewMessageRequest.self, "POST__conversations__id__messages", "request"
        )
        XCTAssertFalse(request.content.isEmpty)
        XCTAssertEqual(request.images, [])
    }

    func testChatStreamEvents() throws {
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__chat_stream", "events.token")
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__chat_stream", "events.reasoning")
        let metrics = try roundTrip(BuddyAPI.ChatMetrics.self, "POST__chat_stream", "events.finished")
        XCTAssertNotNil(metrics.timeToFirstToken)
        try roundTrip(ControlAPI.ErrorResponse.self, "POST__chat_stream", "events.error")
    }

    func testConversationStreamEvents() throws {
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__conversations__id__messages", "events.token")
        try roundTrip(
            BuddyAPI.ChatMetrics.self, "POST__conversations__id__messages", "events.finished"
        )
    }

    func testServerEvents() throws {
        try roundTrip(ControlAPI.Status.self, "GET__events", "events.status")
        let download = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "events.download")
        XCTAssertEqual(download.progress, 0.42)
        let job = try roundTrip(BuddyAPI.JobProgress.self, "GET__events", "events.job")
        XCTAssertEqual(job.status, "running")
        try roundTrip(BuddyAPI.Heartbeat.self, "GET__events", "events.heartbeat")
    }

    // MARK: - Errors

    func testEveryErrorBodyInTheContractDecodes() throws {
        let bundle = Bundle(for: ContractTests.self)
        let directory = bundle.url(forResource: "contract", withExtension: nil)
        let urls = try FileManager.default.contentsOfDirectory(
            at: directory ?? bundle.bundleURL, includingPropertiesForKeys: nil
        ).filter { $0.pathExtension == "json" }
        XCTAssertGreaterThan(urls.count, 20, "The contract export should be here")

        var checked = 0
        for url in urls {
            guard case .object(let fields) = try JSONValue(data: try Data(contentsOf: url)),
                  case .object(let errors)? = fields["errors"]
            else { continue }
            for (status, body) in errors {
                let data = try JSONEncoder().encode(body)
                let decoded = try JSONDecoder.buddy.decode(ControlAPI.ErrorResponse.self, from: data)
                XCTAssertFalse(
                    decoded.error.isEmpty,
                    "\(url.lastPathComponent) \(status) has an empty message"
                )
                // And the mapping has somewhere to put it.
                let mapped = TransportError.from(
                    status: Int(status) ?? 0, body: data, path: "/x"
                )
                XCTAssertNotNil(mapped, "\(status) should map to an error")
                checked += 1
            }
        }
        XCTAssertGreaterThan(checked, 30, "Every route lists the errors it can answer")
    }

    /// A chat-scope device asking to load a model gets this, and it is not the same
    /// thing as "your token is wrong".
    func testTheScopeRefusalIsNotAnUnpairing() throws {
        let fields = try fixture("POST__load")
        let body = try JSONEncoder().encode(try XCTUnwrap(fields["errors"]?["403"]))
        let error = TransportError.from(status: 403, body: body, path: "/load")
        guard case .forbidden(let message)? = error else {
            return XCTFail("403 should be its own case, not unauthorized")
        }
        XCTAssertTrue(message.contains("chat only"))
        XCTAssertNotEqual(error, .unauthorized)
    }

    // MARK: - Requests this app builds

    func testRequestsEncodeTheWayTheMacReadsThem() throws {
        let load = ControlAPI.LoadRequest(modelID: "bonsai-2-27b", quantization: "PTQ1_0")
        let json = try JSONValue(data: JSONEncoder.buddy.encode(load))
        XCTAssertEqual(json["modelID"], .string("bonsai-2-27b"))
        XCTAssertNil(json["contextLength"], "Absent options must not be sent as null")
    }

    func testANewMessageCarriesContentNotATranscript() throws {
        let request = BuddyAPI.NewMessageRequest(
            content: "What is this?", images: ["data:image/jpeg;base64,AAA"], maxTokens: 2048
        )
        let json = try JSONValue(data: JSONEncoder.buddy.encode(request))
        XCTAssertEqual(json["content"], .string("What is this?"))
        XCTAssertEqual(json["images"]?[0], .string("data:image/jpeg;base64,AAA"))
        XCTAssertEqual(json["maxTokens"], .number(2048))
        XCTAssertNil(json["messages"], "The Mac has the history; this route takes one message")
    }

    func testAnEmptyImageListIsStillSent() throws {
        let request = ControlAPI.ChatRequest(messages: [.init(role: "user", content: "hi")])
        let json = try JSONValue(data: JSONEncoder.buddy.encode(request))
        XCTAssertEqual(json["messages"]?[0]?["images"], .array([]))
    }

    // MARK: - Decoding is forgiving where the Mac says it may be

    func testAStatusFromAnOlderMacStillDecodes() throws {
        let json = Data(#"{"state":"Not loaded","expertStreaming":false}"#.utf8)
        let status = try JSONDecoder.buddy.decode(ControlAPI.Status.self, from: json)
        XCTAssertFalse(status.hasLoadedModel)
    }

    func testAPairResponseWithoutAScopeMeansFull() throws {
        let json = Data(#"{"deviceID":"1","token":"t","macName":"Mac","port":8788}"#.utf8)
        let paired = try JSONDecoder.buddy.decode(BuddyAPI.PairResponse.self, from: json)
        XCTAssertNil(paired.scope)
        XCTAssertEqual(BuddyAPI.DeviceScope(wire: paired.scope), .full)
    }

    func testConversationTimestampsDecodeBothISOSpellings() throws {
        let withFraction = Data(#"{"id":"1","title":"t","updatedAt":"2026-09-18T10:11:12.345Z","messageCount":2}"#.utf8)
        let plain = Data(#"{"id":"1","title":"t","updatedAt":"2026-09-18T10:11:12Z","messageCount":2}"#.utf8)
        XCTAssertNoThrow(try JSONDecoder.buddy.decode(BuddyAPI.ConversationSummary.self, from: withFraction))
        XCTAssertNoThrow(try JSONDecoder.buddy.decode(BuddyAPI.ConversationSummary.self, from: plain))
    }
}
