import XCTest
@testable import SiliconBuddy

/// The mirrored types, checked against the Mac's own export.
///
/// `contract/` is generated by silicon-optimizer's `ContractExportTests` — the shapes
/// its wire types actually encode, not something written by hand here. Each file holds
/// a route: its request, its response, the events it can send and the errors it can
/// answer. The round trip is the part that matters: decode, re-encode, compare the
/// JSON. A field this app forgot to mirror disappears in the re-encode, so the
/// comparison fails — which is the drift that would otherwise be discovered by a
/// person staring at a blank row.
final class ContractTests: XCTestCase {

    // MARK: - Fixtures

    private func fixture(_ name: String) throws -> [String: JSONValue] {
        let bundle = Bundle(for: ContractTests.self)
        let url = try XCTUnwrap(
            bundle.url(forResource: name, withExtension: "json", subdirectory: "contract")
                ?? bundle.url(forResource: name, withExtension: "json"),
            "Missing fixture \(name).json — run contract/refresh.sh"
        )
        let value = try JSONValue(data: try Data(contentsOf: url))
        guard case .object(let fields) = value else {
            throw XCTSkip("\(name).json is not a route fixture")
        }
        return fields
    }

    /// Decodes one part of a fixture — `response`, `request`, or one named event — then
    /// re-encodes it and compares field by field.
    @discardableResult
    private func roundTrip<T: Codable & Equatable>(
        _ type: T.Type, _ name: String, _ part: String = "response",
        file: StaticString = #filePath, line: UInt = #line
    ) throws -> T {
        let fields = try fixture(name)
        let piece: JSONValue
        if part.hasPrefix("events.") {
            let event = String(part.dropFirst("events.".count))
            piece = try XCTUnwrap(
                fields["events"]?[event], "\(name) has no \(part)", file: file, line: line
            )
        } else if part.hasPrefix("errors.") {
            let status = String(part.dropFirst("errors.".count))
            piece = try XCTUnwrap(
                fields["errors"]?[status], "\(name) has no \(part)", file: file, line: line
            )
        } else if part.hasPrefix("requests.") {
            // `requests.cancel`: one of the bodies a route with several verbs takes.
            let verb = String(part.dropFirst("requests.".count))
            piece = try XCTUnwrap(
                fields["requests"]?[verb], "\(name) has no \(part)", file: file, line: line
            )
        } else if part.hasPrefix("responseVariants.") {
            // `responseVariants.still loading`: another answer the same route can give.
            let label = String(part.dropFirst("responseVariants.".count))
            piece = try XCTUnwrap(
                fields["responseVariants"]?[label], "\(name) has no \(part)", file: file, line: line
            )
        } else if part.hasPrefix("errorVariants.") {
            // `errorVariants.409.still screening`: one more refusal a status can carry.
            let path = part.dropFirst("errorVariants.".count)
            let status = String(path.prefix { $0 != "." })
            let label = String(path.dropFirst(status.count + 1))
            piece = try XCTUnwrap(
                fields["errorVariants"]?[status]?[label], "\(name) has no \(part)",
                file: file, line: line
            )
        } else if part.hasPrefix("eventVariants.") {
            // `eventVariants.agent.approval answered`: one named variant of one event.
            let path = part.dropFirst("eventVariants.".count)
            let event = String(path.prefix { $0 != "." })
            let variant = String(path.dropFirst(event.count + 1))
            piece = try XCTUnwrap(
                fields["eventVariants"]?[event]?[variant], "\(name) has no \(part)",
                file: file, line: line
            )
        } else {
            piece = try XCTUnwrap(fields[part], "\(name) has no \(part)", file: file, line: line)
        }

        let data = try JSONEncoder().encode(piece)
        let decoded: T
        do {
            decoded = try JSONDecoder.buddy.decode(type, from: data)
        } catch {
            XCTFail("\(name).\(part) does not decode as \(type): \(error)", file: file, line: line)
            throw error
        }
        let reencoded = try JSONEncoder.buddy.encode(decoded)
        XCTAssertEqual(
            decoded, try JSONDecoder.buddy.decode(type, from: reencoded),
            "\(name).\(part) changed shape on a round trip", file: file, line: line
        )

        let original = piece.strippingNulls()
        let rebuilt = try JSONValue(data: reencoded).strippingNulls()
        if original != rebuilt {
            XCTFail(
                "\(name).\(part) lost or changed fields on a round trip:\n"
                    + original.difference(from: rebuilt).joined(separator: "\n"),
                file: file, line: line
            )
        }
        return decoded
    }

    // MARK: - The routes this app calls today

    func testHealth() throws {
        let health = try roundTrip(ControlAPI.Health.self, "GET__health")
        XCTAssertEqual(health.status, "ok")
        // The Mac's own version and build (OGZamasu/silicon-optimizer#81), as a device shows them.
        XCTAssertEqual(health.appVersionLabel, "0.5.0 (157)")
    }

    func testStatus() throws {
        let status = try roundTrip(ControlAPI.Status.self, "GET__status")
        XCTAssertTrue(status.hasLoadedModel)
    }

    func testProfile() throws {
        let profile = try roundTrip(ControlAPI.Profile.self, "GET__profile")
        XCTAssertFalse(profile.chip.isEmpty)
        XCTAssertGreaterThan(profile.totalMemoryBytes, 0)
    }

    func testMetrics() throws {
        let metrics = try roundTrip(ControlAPI.Metrics.self, "GET__metrics")
        XCTAssertGreaterThan(metrics.memoryTotalBytes, 0)
    }

    func testInstalled() throws {
        XCTAssertFalse(try roundTrip([ControlAPI.InstalledModel].self, "GET__installed").isEmpty)
    }

    func testCatalog() throws {
        let catalog = try roundTrip([ControlAPI.CatalogModel].self, "GET__catalog")
        XCTAssertTrue(catalog.contains { $0.recommendation != nil })
    }

    func testRecommend() throws {
        try roundTrip(ControlAPI.CatalogModel.self, "GET__recommend")
    }

    func testSwarm() throws {
        let swarm = try roundTrip(ControlAPI.SwarmView.self, "GET__swarm")
        let peer = try XCTUnwrap(swarm.peers.first)
        XCTAssertEqual(peer.hardware, "NVIDIA GeForce RTX 3090 Ti")
        XCTAssertNotNil(peer.loadedModel)
        XCTAssertNotNil(peer.lanes)
    }

    /// One node asked now: the only place the adapter on its loaded GGUF appears.
    func testPeerStatus() throws {
        let peer = try roundTrip(ControlAPI.PeerNodeStatus.self, "GET__swarm_peers__name__status")
        XCTAssertEqual(peer.gguf?.adapter, "bonsai-27b-v3.lora.gguf")
        XCTAssertFalse(peer.gguf?.installedModels.isEmpty ?? true)
    }

    /// A picture sent from a device comes back as the ids a render starts from.
    func testUpload() throws {
        let upload = try roundTrip(ControlAPI.UploadResponse.self, "POST__uploads")
        XCTAssertEqual(upload.mediaURL, "/media/\(upload.mediaID)")
        XCTAssertFalse(upload.uploadID.isEmpty)
    }

    /// `GET /media/{id}` answers bytes, so there is no response to round-trip — only
    /// the scopes and the errors, which the export-wide tests below account for.
    func testMediaAnswersBytes() throws {
        let fields = try fixture("GET__media__id_")
        XCTAssertEqual(fields["response"], JSONValue.null)
        guard case .object(let errors)? = fields["errors"] else {
            return XCTFail("GET /media/{id} documents no errors")
        }
        XCTAssertNotNil(errors["403"], "a chat-only device is refused the renders themselves")
        XCTAssertNotNil(errors["416"])
    }

    func testNodeAdvertisement() throws {
        let node = try roundTrip(ControlAPI.NodeAdvertisement.self, "GET__v1_node")
        XCTAssertGreaterThan(node.profile.memoryGB, 0, "snake_case keys must map")
    }

    func testVideoModels() throws {
        let lane = try XCTUnwrap(
            try roundTrip([ControlAPI.VideoModel].self, "GET__video_models").first
        )
        XCTAssertEqual(lane.supportedResolutions, ["480p", "720p", "1080p"])
        XCTAssertEqual(lane.supportsNegativePrompt, true)
    }

    func testVideoQueue() throws {
        let queue = try roundTrip(ControlAPI.VideoQueueView.self, "GET__video_queue")
        let done = try XCTUnwrap(queue.items.first { $0.status == "completed" })
        XCTAssertNotNil(done.mediaID)
        XCTAssertNotNil(done.thumbnailMediaID)
        try roundTrip(ControlAPI.VideoQueueView.self, "POST__video_queue")
    }

    /// Seven verbs, each with a fixture of its own, and no eighth.
    func testControllingTheQueue() throws {
        guard case .object(let requests)? = try fixture("POST__video_queue_control")["requests"] else {
            return XCTFail("POST__video_queue_control has no requests")
        }
        let verbs = Set(requests.keys)
        XCTAssertEqual(verbs, [
            ControlAPI.VideoQueueControl.pause, ControlAPI.VideoQueueControl.resume,
            ControlAPI.VideoQueueControl.retry, ControlAPI.VideoQueueControl.remove,
            ControlAPI.VideoQueueControl.stopFollowing, ControlAPI.VideoQueueControl.cancel,
            ControlAPI.VideoQueueControl.clearFinished,
        ])
        for verb in verbs.sorted() {
            let sent = try roundTrip(
                ControlAPI.VideoQueueControl.self, "POST__video_queue_control", "requests.\(verb)"
            )
            XCTAssertEqual(sent.action, verb)
            XCTAssertEqual(
                sent.id != nil, ControlAPI.VideoQueueControl.needsID.contains(verb),
                "\(verb) names an item exactly when it needs one"
            )
        }
        XCTAssertEqual(
            try roundTrip(ControlAPI.VideoQueueControl.self, "POST__video_queue_control", "requests.retry")
                .confirmNewRender, true, "retry is the one that has to be meant"
        )
        try roundTrip(ControlAPI.VideoQueueView.self, "POST__video_queue_control")
        let swarm = try roundTrip(
            ControlAPI.ErrorResponse.self, "POST__video_queue_control", "errorVariants.403.swarm"
        )
        XCTAssertTrue(swarm.error.contains("swarm"), "the swarm secret is refused every verb")
    }

    /// `cancel` names the one clip the Mac marked `canCancel`; whether it applies is the
    /// Mac's answer per item, never this app's guess.
    func testCancellingARenderNamesTheClipTheMacSaysCanBeCancelled() throws {
        let sent = try roundTrip(
            ControlAPI.VideoQueueControl.self, "POST__video_queue_control", "requests.cancel"
        )
        XCTAssertEqual(sent.action, ControlAPI.VideoQueueControl.cancel)
        XCTAssertNil(sent.confirmNewRender)
        for name in ["GET__video_queue", "POST__video_queue", "POST__video_queue_control"] {
            let items = try roundTrip(ControlAPI.VideoQueueView.self, name).items
            XCTAssertEqual(
                items.filter { $0.offersCancelRender(canControl: true) }.map(\.id), [sent.id],
                "\(name) offers Cancel render on exactly the clip it marks"
            )
            XCTAssertFalse(items.contains { $0.offersCancelRender(canControl: false) })
            let cancelled = try XCTUnwrap(items.first { $0.status == "cancelled" })
            XCTAssertEqual(QueueCancelState(wire: cancelled.cancelState), .confirmed)
            XCTAssertEqual(cancelled.phase, .cancelled)
            XCTAssertFalse(cancelled.cancelDetail?.isEmpty ?? true)
        }
    }

    func testImageModels() throws {
        try roundTrip([ControlAPI.ImageModel].self, "GET__image_models")
    }

    func testMeshModels() throws {
        try roundTrip([ControlAPI.MeshModel].self, "GET__mesh_models")
    }

    func testChat() throws {
        try roundTrip(ControlAPI.ChatRequest.self, "POST__chat", "request")
        XCTAssertFalse(try roundTrip(ControlAPI.ChatResponse.self, "POST__chat").content.isEmpty)
    }

    func testLoadAndInstall() throws {
        try roundTrip(ControlAPI.LoadRequest.self, "POST__load", "request")
        try roundTrip(ControlAPI.Status.self, "POST__load")
        // A load slower than the request's patience: the live status, nothing resident yet,
        // and nothing claimed to have failed — the load carries on on the Mac.
        let stillLoading = try roundTrip(ControlAPI.Status.self, "POST__load", "responseVariants.still loading")
        XCTAssertNil(stillLoading.loadedModelID)
        XCTAssertNil(stillLoading.failure)
        // A second load while one runs is refused, and the phone is told it as a conflict.
        let body = try JSONEncoder().encode(try XCTUnwrap(try fixture("POST__load")["errors"]?["409"]))
        guard case .conflict(let message)? = TransportError.from(status: 409, body: body, path: "/load") else {
            return XCTFail("409 on /load should be a conflict")
        }
        XCTAssertTrue(message.contains("Nothing was changed"))
        try roundTrip(ControlAPI.LoadRequest.self, "POST__install", "request")
        try roundTrip(ControlAPI.StatusMessage.self, "POST__install")
        try roundTrip(ControlAPI.StatusMessage.self, "POST__unload")
    }

    func testPlanRequest() throws {
        try roundTrip(ControlAPI.PlanRequest.self, "POST__plan", "request")
        XCTAssertNil(
            try roundTrip(ControlAPI.Plan.self, "POST__plan").recurrentStateBytes,
            "an ordinary model has no recurrent state"
        )
    }

    /// A hybrid model's plan (OGZamasu/silicon-optimizer#26) carries its fixed
    /// linear-attention state. The exported example is not a hybrid, so the field is added
    /// to it here — and it has to survive the round trip, which it would not unmirrored.
    func testAHybridModelsPlanCarriesItsRecurrentState() throws {
        guard case .object(var plan)? = try fixture("POST__plan")["response"] else {
            return XCTFail("POST__plan has no response")
        }
        plan["recurrentStateBytes"] = .number(301_989_888)
        let decoded = try JSONDecoder.buddy.decode(
            ControlAPI.Plan.self, from: try JSONEncoder().encode(JSONValue.object(plan))
        )
        XCTAssertEqual(decoded.recurrentStateBytes, 301_989_888)
        let rebuilt = try JSONValue(data: try JSONEncoder.buddy.encode(decoded)).strippingNulls()
        XCTAssertEqual(rebuilt, JSONValue.object(plan).strippingNulls())
    }

    // MARK: - The M0 routes

    func testPairing() throws {
        try roundTrip(BuddyAPI.PairRequest.self, "POST__buddy_pair", "request")
        let paired = try roundTrip(BuddyAPI.PairResponse.self, "POST__buddy_pair")
        XCTAssertEqual(BuddyAPI.DeviceScope(wire: paired.scope), .full)
        XCTAssertFalse(paired.token.isEmpty)
    }

    func testPairedDevices() throws {
        let devices = try roundTrip([BuddyAPI.PairedDevice].self, "GET__buddy_devices")
        XCTAssertEqual(devices.first?.scope, "full")
        try roundTrip(ControlAPI.StatusMessage.self, "DELETE__buddy_devices__id_")
    }

    func testConversations() throws {
        let summaries = try roundTrip([BuddyAPI.ConversationSummary].self, "GET__conversations")
        XCTAssertEqual(summaries.first?.messageCount, 2)
        try roundTrip(BuddyAPI.NewConversation.self, "POST__conversations", "request")
        try roundTrip(BuddyAPI.ConversationSummary.self, "POST__conversations")
    }

    func testConversationDetail() throws {
        let detail = try roundTrip(BuddyAPI.ConversationDetail.self, "GET__conversations__id_")
        XCTAssertFalse(detail.isGenerating)
        XCTAssertEqual(detail.messages.count, 2)
    }

    /// The route this app got wrong once: it takes one message, not a transcript.
    func testSendingAMessageToAConversation() throws {
        let request = try roundTrip(
            BuddyAPI.NewMessageRequest.self, "POST__conversations__id__messages", "request"
        )
        XCTAssertFalse(request.content.isEmpty)
        XCTAssertEqual(request.images, [])
    }

    func testChatStreamEvents() throws {
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__chat_stream", "events.token")
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__chat_stream", "events.reasoning")
        let metrics = try roundTrip(BuddyAPI.ChatMetrics.self, "POST__chat_stream", "events.finished")
        XCTAssertNotNil(metrics.timeToFirstToken)
        try roundTrip(ControlAPI.ErrorResponse.self, "POST__chat_stream", "events.error")
    }

    func testConversationStreamEvents() throws {
        try roundTrip(BuddyAPI.TokenEvent.self, "POST__conversations__id__messages", "events.token")
        try roundTrip(
            BuddyAPI.ChatMetrics.self, "POST__conversations__id__messages", "events.finished"
        )
    }

    func testServerEvents() throws {
        try roundTrip(ControlAPI.Status.self, "GET__events", "events.status")
        let download = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "events.download")
        XCTAssertEqual(download.progress, 0.42)
        let job = try roundTrip(BuddyAPI.JobProgress.self, "GET__events", "events.job")
        XCTAssertEqual(job.stage, "video-denoise 18/30")
        XCTAssertEqual(job.status, "running")
        try roundTrip(BuddyAPI.Heartbeat.self, "GET__events", "events.heartbeat")
    }


    // MARK: - M5: the models the Mac keeps for the phone (types only on iOS for now)

    func testThePhonesModelsArePinnedWithTheMacsCopyAndARealPhonesNumbers() throws {
        let list = try roundTrip(OnDeviceAPI.PhoneModelList.self, "GET__ondevice_models")
        let qwen = try XCTUnwrap(list.models.first { $0.isDefault })
        XCTAssertEqual(qwen.id, "qwen3.5-2b-q4_0")
        XCTAssertEqual(qwen.sizeBytes, 1_296_764_000)
        XCTAssertEqual(qwen.sha256, "91c102fc9a86de80e427057ee938e1e34fcaf3bba956b7296e252406e05f36f6")
        XCTAssertEqual(qwen.source.commit, "7d26695454df6de5fbcce2e58681e62dae06ce43")
        XCTAssertTrue(qwen.onMac.isReady)
        XCTAssertEqual(qwen.recommended.threadsPrompt, 6)
        XCTAssertEqual(qwen.recommended.threadsGenerate, 4)
        XCTAssertEqual(qwen.recommended.contextLength, 4096)
        XCTAssertEqual(qwen.recommended.minFreeMemoryBytes, 3_100_000_000)
        XCTAssertFalse(qwen.recommended.thinking)
        XCTAssertEqual(qwen.measured?.secondsToFirstWord300, 2.5)
        XCTAssertNil(qwen.measured?.sustainedTokensPerSecond, "not measured is not claimed")
        // The Mac lists more than one alternative now; each is found by its id.
        let gemma = try XCTUnwrap(list.models.first { $0.id == "gemma-4-e2b-q4_0" })
        XCTAssertFalse(gemma.isDefault)
        XCTAssertEqual(list.models.filter(\.isDefault).count, 1, "only one default")
        XCTAssertTrue(gemma.slowerOnPhone)
        XCTAssertEqual(gemma.recommended.minFreeMemoryBytes, 4_700_000_000)
        XCTAssertEqual(gemma.onMac.state, "failed")
        XCTAssertEqual(gemma.onMac.failure, "network")
    }

    func testPrepareAndDeleteAnswerTheEntryItself() throws {
        let prepared = try roundTrip(OnDeviceAPI.PhoneModel.self, "POST__ondevice_models__id__prepare")
        XCTAssertEqual(prepared.downloadEventID, "ondevice:\(prepared.id)")
        try roundTrip(OnDeviceAPI.PhoneModel.self, "DELETE__ondevice_models__id_")
        XCTAssertEqual(try fixture("POST__ondevice_models__id__prepare")["request"], JSONValue.null)
        XCTAssertEqual(try fixture("GET__ondevice_models__id__file")["response"], JSONValue.null, "the file is bytes")
    }

    func testThePhoneModelRefusalsMapToCasesOfTheirOwn() throws {
        func mapped(_ name: String, _ status: String) throws -> TransportError? {
            let body = try JSONEncoder().encode(try XCTUnwrap(try fixture(name)["errors"]?[status]))
            return TransportError.from(status: Int(status)!, body: body, path: "/x")
        }
        guard case .conflict? = try mapped("GET__ondevice_models__id__file", "409") else {
            return XCTFail("409 is the Mac's copy not being ready yet")
        }
        guard case .rangeNotSatisfiable? = try mapped("GET__ondevice_models__id__file", "416") else {
            return XCTFail("416 is a range past the end")
        }
        guard case .unavailable(let drive)? = try mapped("GET__ondevice_models__id__file", "503") else {
            return XCTFail("503 is the Mac's library drive being gone")
        }
        XCTAssertTrue(drive.contains("is not connected"))
        guard case .insufficientStorage? = try mapped("POST__ondevice_models__id__prepare", "507") else {
            return XCTFail("507 is no room on the Mac")
        }
    }

    func testTheMacFetchingAPhoneModelArrivesAsDownloadFramesWithAStage() throws {
        let fetching = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model")
        XCTAssertTrue(fetching.isPhoneModel)
        XCTAssertEqual(fetching.stage, "fetching")
        let checking = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model checking")
        XCTAssertEqual(checking.stage, "checking")
        let moving = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model moving")
        XCTAssertEqual(moving.stage, "moving")
        let ready = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model ready")
        XCTAssertNil(ready.stage, "done has no stage")
        XCTAssertEqual(ready.progress, 1)
        let failed = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model failed")
        XCTAssertTrue(failed.error?.contains("checksum") == true)
        let removed = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "eventVariants.download.phone model removed")
        XCTAssertEqual(removed.error, "Removed from the Mac before it finished.")
        let mac = try roundTrip(BuddyAPI.DownloadProgress.self, "GET__events", "events.download")
        XCTAssertFalse(mac.isPhoneModel, "the Mac's own downloads are not the phone's")
    }

    // MARK: - The M4 routes: the Mac's agent sessions (types only on iOS for now)

    func testAgentSessionList() throws {
        let list = try roundTrip(AgentAPI.SessionList.self, "GET__agent_sessions")
        XCTAssertEqual(list.sessions.map(\.engine), ["codex", "pi"])
        XCTAssertEqual(list.sessions.first?.pendingApprovals, 1)
        XCTAssertNotNil(list.sessions.first?.threadID, "Codex mints a thread id")
        XCTAssertNil(list.sessions.last?.threadID, "Pi has none to give")
        XCTAssertEqual(list.sessions.first?.approvals, "screened")
        XCTAssertEqual(list.sessions.last?.approvals, "unattended")
        XCTAssertEqual(list.sessions.last?.sandbox, "none")
        XCTAssertTrue(list.sessions.first?.cwd?.hasPrefix("~/") ?? false, "never the absolute home path")
    }

    func testAgentSessionDetail() throws {
        let detail = try roundTrip(AgentAPI.SessionDetail.self, "GET__agent_sessions__engine_")
        XCTAssertTrue(detail.complete)
        XCTAssertEqual(detail.seq, 41)
        XCTAssertEqual(
            detail.items.map(\.kind), ["user", "reasoning", "assistant", "command", "fileChange"]
        )
        XCTAssertNotNil(detail.items.first { $0.kind == "command" }?.output)
        XCTAssertEqual(detail.items.first { $0.kind == "command" }?.truncated, true)
        XCTAssertEqual(detail.approvals.first?.summary, "rm -rf .build")
        XCTAssertEqual(detail.approvals.first?.screening.verdict, "confirm")
        XCTAssertEqual(detail.epoch, detail.session.epoch, "the cursor's two halves agree")
        XCTAssertEqual(detail.omitted, 0)
    }

    func testAgentVerbsAnswerTheSummary() throws {
        XCTAssertEqual(
            try roundTrip(AgentAPI.SessionSummary.self, "POST__agent_sessions__engine__start").state,
            "running"
        )
        XCTAssertEqual(
            try roundTrip(AgentAPI.SessionSummary.self, "POST__agent_sessions__engine__new").itemCount,
            0
        )
        try roundTrip(AgentAPI.SessionSummary.self, "POST__agent_sessions__engine__interrupt")
        XCTAssertEqual(
            try roundTrip(AgentAPI.SessionSummary.self, "DELETE__agent_sessions__engine_").state,
            "stopped"
        )
    }

    func testSendingAnAgentTurn() throws {
        let request = try roundTrip(
            AgentAPI.MessageRequest.self, "POST__agent_sessions__engine__messages", "request"
        )
        XCTAssertEqual(request.model, "local/qwen3-coder-30b")
        XCTAssertFalse(
            try roundTrip(AgentAPI.MessageAccepted.self, "POST__agent_sessions__engine__messages")
                .itemID.isEmpty
        )
    }

    func testAnsweringAnApproval() throws {
        let request = try roundTrip(
            AgentAPI.ApprovalDecision.self, "POST__agent_sessions__engine__approvals__id_", "request"
        )
        XCTAssertEqual(request.decision, "accept")
        let result = try roundTrip(
            AgentAPI.ApprovalResult.self, "POST__agent_sessions__engine__approvals__id_"
        )
        XCTAssertEqual(result.decision, "accepted")
        XCTAssertEqual(result.session.pendingApprovals, 0)

        let fields = try fixture("POST__agent_sessions__engine__approvals__id_")
        let conflict = try JSONEncoder().encode(try XCTUnwrap(fields["errors"]?["409"]))
        guard case .conflict(let message)? = TransportError.from(status: 409, body: conflict, path: "/x")
        else { return XCTFail("answered at the Mac first should be its own case") }
        XCTAssertTrue(message.contains("answered at the Mac"))
    }

    func testAgentFrames() throws {
        let item = try roundTrip(AgentAPI.Event.self, "GET__events", "events.agent")
        XCTAssertEqual(item.kind, "item")
        XCTAssertNotNil(item.item)
        XCTAssertEqual(
            try roundTrip(AgentAPI.Event.self, "GET__events", "eventVariants.agent.state").state,
            "running"
        )
        XCTAssertEqual(
            try roundTrip(AgentAPI.Event.self, "GET__events", "eventVariants.agent.turn").turnActive,
            true
        )
        let asked = try roundTrip(AgentAPI.Event.self, "GET__events", "eventVariants.agent.approval")
        let answered = try roundTrip(
            AgentAPI.Event.self, "GET__events", "eventVariants.agent.approval answered"
        )
        XCTAssertEqual(asked.state, "pending")
        XCTAssertEqual(answered.state, "accepted")
        XCTAssertEqual(asked.approval?.id, answered.approval?.id)
        let reset = try roundTrip(AgentAPI.Event.self, "GET__events", "eventVariants.agent.reset")
        XCTAssertEqual(reset.kind, "reset")
        XCTAssertNotEqual(reset.epoch, item.epoch, "a reset names the transcript that replaced it")
        XCTAssertEqual(
            try roundTrip(AgentAPI.Resync.self, "GET__events", "events.resync").dropped, 7
        )
    }

    /// Every `errorVariants` entry the export carries, pinned like the fixtures.
    static let expectedErrorVariants: Set<String> = [
        "DELETE__agent_sessions__engine_ 403 swarm",
        "GET__agent_sessions 403 swarm",
        "GET__agent_sessions__engine_ 403 swarm",
        "POST__agent_sessions__engine__approvals__id_ 403 swarm",
        "POST__agent_sessions__engine__approvals__id_ 409 engine stopped",
        "POST__agent_sessions__engine__approvals__id_ 409 still screening",
        "POST__agent_sessions__engine__interrupt 403 swarm",
        "POST__agent_sessions__engine__messages 403 swarm",
        "POST__agent_sessions__engine__messages 409 turn in progress",
        "POST__agent_sessions__engine__new 403 swarm",
        "POST__agent_sessions__engine__start 403 swarm",
        "POST__agent_sessions__engine__start 409 stopping",
        "DELETE__ondevice_models__id_ 403 swarm",
        "GET__ondevice_models 403 swarm",
        "GET__ondevice_models__id__file 403 swarm",
        "POST__ondevice_models__id__prepare 403 swarm",
        // The queue's controls are the owner's: the swarm secret is refused every verb.
        "POST__video_queue_control 403 swarm",
        // A load this Mac stopped before it finished (OGZamasu/silicon-optimizer#97).
        "POST__load 409 replaced by another load before it finished",
        "POST__load 409 stopped by an unload before it finished",
    ]

    /// The refusals a status can carry beyond the one in `errors`, read strictly: each is
    /// `{status: {label: {error}}}`, decodes, maps to a case of its own rather than
    /// `.server`, and the set is pinned so a new one fails here first.
    func testEveryErrorVariantDecodesAndMaps() throws {
        var seen: Set<String> = []
        for name in Self.expectedFixtures.sorted() {
            let fields = try fixture(name)
            guard let variants = fields["errorVariants"] else { continue }
            guard case .object(let statuses) = variants else {
                return XCTFail("\(name): errorVariants is not an object")
            }
            for (status, labels) in statuses {
                let code = try XCTUnwrap(Int(status), "\(name): \(status) is not a status")
                guard case .object(let bodies) = labels else {
                    return XCTFail("\(name) \(status): labels are not an object")
                }
                for (label, body) in bodies {
                    guard case .object(let keys) = body, Set(keys.keys) == ["error"] else {
                        return XCTFail("\(name) \(status) \(label): a body is {error}")
                    }
                    let data = try JSONEncoder().encode(body)
                    let decoded = try JSONDecoder.buddy.decode(ControlAPI.ErrorResponse.self, from: data)
                    XCTAssertFalse(decoded.error.isEmpty, "\(name) \(status) \(label) says nothing")
                    let mapped = try XCTUnwrap(TransportError.from(status: code, body: data, path: "/x"))
                    if case .server = mapped {
                        XCTFail("\(name) \(status) \(label) falls through to .server")
                    }
                    seen.insert("\(name) \(status) \(label)")
                }
            }
        }
        XCTAssertEqual(
            seen, Self.expectedErrorVariants,
            "The Mac documents different refusals now — refresh, map them, then list them here"
        )
        let screening = try JSONEncoder().encode(
            try XCTUnwrap(try fixture("POST__agent_sessions__engine__approvals__id_")["errorVariants"]?["409"]?["still screening"])
        )
        guard case .conflict? = TransportError.from(status: 409, body: screening, path: "/x") else {
            return XCTFail("still screening is a conflict to explain, not an error to show")
        }
    }

    // MARK: - The export itself

    /// The contract is a copy of something generated elsewhere, and a copy goes stale
    /// quietly. This is the test that makes it loud: the set of routes, and the errors
    /// each one documents, are the Mac's answers as of the last refresh. When they
    /// change, `contract/refresh.sh` is the fix — not this list.
    static let expectedFixtures: Set<String> = [
        // Two routes the Mac grew so that tests and CLIs can pair at all: pairing
        // codes used to be mintable only from its own Settings window. They are
        // loopback-and-control-token only, which means no device can ever reach them
        // — this app included, whatever it is holding. Listed because the export is
        // the whole export; deliberately not mirrored, because a type for a route
        // this app is forbidden to call would be a type nothing can ever use.
        // The Jev routes and the task-shaped `POST /recommend` are listed so the
        // export is accounted for; no type here mirrors them yet, because nothing in
        // this app speaks them. The three media routes M3 added are mirrored as
        // types — `POST /uploads` and `GET /swarm/peers/{name}/status` answer JSON,
        // and `GET /media/{id}` answers bytes, so it has none — ahead of the iOS
        // screens that will call them.
        "DELETE__agent_sessions__engine_",
        "DELETE__buddy_devices__id_",
        "DELETE__buddy_invitations",
        // M5: the models the Mac keeps for the phone, mirrored in `OnDeviceAPI.swift`.
        "DELETE__ondevice_models__id_",
        "GET__ondevice_models",
        "GET__ondevice_models__id__file",
        "POST__ondevice_models__id__prepare",
        "GET__agent_sessions",
        "GET__agent_sessions__engine_",
        "GET__buddy_devices",
        "GET__catalog",
        "GET__conversations",
        "GET__conversations__id_",
        "GET__events",
        "GET__health",
        "GET__image_models",
        "GET__installed",
        "GET__jev",
        "GET__jev_calibration",
        "GET__jev_guardrails_recent",
        "GET__media__id_",
        "GET__mesh_models",
        "GET__metrics",
        "GET__profile",
        "GET__recommend",
        "GET__status",
        "GET__swarm",
        "GET__swarm_peers__name__status",
        "GET__v1_node",
        "GET__video_models",
        "GET__video_queue",
        "POST__agent_sessions__engine__approvals__id_",
        "POST__agent_sessions__engine__interrupt",
        "POST__agent_sessions__engine__messages",
        "POST__agent_sessions__engine__new",
        "POST__agent_sessions__engine__start",
        "POST__benchmark",
        "POST__buddy_invitations",
        "POST__buddy_pair",
        "POST__chat",
        "POST__chat_stream",
        "POST__conversations",
        "POST__conversations__id__messages",
        "POST__decide",
        "POST__image_generate",
        "POST__image_plan",
        "POST__install",
        "POST__jev",
        "POST__jev_calibrate",
        "POST__load",
        "POST__mesh_generate",
        "POST__mesh_plan",
        "POST__plan",
        "POST__recommend",
        "POST__unload",
        "POST__uploads",
        "POST__v1_systemone",
        "POST__video_generate",
        "POST__video_queue",
        "POST__video_queue_control"
    ]

    func testTheContractIsTheWholeExportAndNothingElse() throws {
        let bundle = Bundle(for: ContractTests.self)
        let directory = try XCTUnwrap(
            bundle.url(forResource: "contract", withExtension: nil) ?? bundle.resourceURL
        )
        let files = try FileManager.default.contentsOfDirectory(
            at: directory, includingPropertiesForKeys: nil
        )
        let fixtures = Set(
            files.filter { $0.pathExtension == "json" }
                .map { $0.deletingPathExtension().lastPathComponent }
        )
        let missing = Self.expectedFixtures.subtracting(fixtures).sorted()
        let extra = fixtures.subtracting(Self.expectedFixtures).sorted()
        XCTAssertTrue(
            missing.isEmpty,
            "The contract is missing \(missing.joined(separator: ", ")) — run contract/refresh.sh"
        )
        XCTAssertTrue(
            extra.isEmpty,
            "The Mac grew \(extra.joined(separator: ", ")) — mirror them, then add them here"
        )
        XCTAssertTrue(
            files.contains { $0.lastPathComponent == "routes.md" },
            "routes.md comes with the export"
        )
    }

    /// Every status any route documents has a case of its own. A new one falling into
    /// `.server` would reach a person as a number.
    func testEveryDocumentedStatusIsMapped() throws {
        var seen: Set<Int> = []
        for name in Self.expectedFixtures.sorted() {
            let fields = try fixture(name)
            guard case .object(let errors)? = fields["errors"] else { continue }
            for (status, body) in errors {
                let code = try XCTUnwrap(Int(status))
                seen.insert(code)
                let mapped = TransportError.from(
                    status: code, body: try JSONEncoder().encode(body), path: "/x"
                )
                let error = try XCTUnwrap(mapped, "\(name) documents \(code); nothing maps it")
                // A 500 is a server error and `.server` is what it is; what matters is
                // that it reaches a person as the Mac's own sentence rather than a
                // number, which the next assertion checks. Every other status needs a
                // case of its own.
                if case .server(let number, _) = error, number != 500 {
                    XCTFail("\(name) documents \(number) and it falls through to .server")
                }
                XCTAssertFalse(
                    (error.errorDescription ?? "").isEmpty,
                    "\(name) \(code) reaches a person as nothing"
                )
            }
        }
        XCTAssertEqual(
            // 503 and 507 arrived with the phone's models: the Mac's library drive gone,
            // and no room on the Mac.
            seen, [400, 401, 403, 404, 409, 411, 413, 415, 416, 429, 500, 503, 507],
            "The statuses the Mac documents changed — run contract/refresh.sh, then map them"
        )
    }

    /// Three things the current export says that an older copy did not. A stale
    /// contract/ fails here rather than being discovered on a phone.
    func testTheExportIsTheCurrentOne() throws {
        for name in Self.expectedFixtures.sorted() where name.hasPrefix("POST__") {
            // Every POST but the ones that take no body at all documents a 400 — three
            // from before, and the three agent verbs, whose fixtures say `"request": null`.
            let bodiless = [
                "POST__benchmark", "POST__unload", "POST__jev_calibrate",
                "POST__agent_sessions__engine__start", "POST__agent_sessions__engine__new",
                "POST__agent_sessions__engine__interrupt",
            ]
            if bodiless.contains(name) {
                XCTAssertEqual(try fixture(name)["request"], JSONValue.null, "\(name) takes no body")
                continue
            }
            let fields = try fixture(name)
            guard case .object(let errors)? = fields["errors"] else {
                return XCTFail("\(name) documents no errors at all")
            }
            XCTAssertNotNil(errors["400"], "\(name) should document a 400 — refresh the contract")
        }
        for name in ["GET__recommend", "GET__conversations__id_", "DELETE__buddy_devices__id_"] {
            let fields = try fixture(name)
            guard case .object(let errors)? = fields["errors"] else { continue }
            XCTAssertNotNil(errors["404"], "\(name) should document a 404 — refresh the contract")
        }
        for name in ["POST__chat_stream", "POST__conversations__id__messages", "GET__events"] {
            let fields = try fixture(name)
            guard case .object(let errors)? = fields["errors"] else { continue }
            XCTAssertNotNil(errors["429"], "\(name) should document a 429 — refresh the contract")
        }
    }

    // MARK: - Errors

    func testEveryErrorBodyInTheContractDecodes() throws {
        let bundle = Bundle(for: ContractTests.self)
        let directory = bundle.url(forResource: "contract", withExtension: nil)
        let urls = try FileManager.default.contentsOfDirectory(
            at: directory ?? bundle.bundleURL, includingPropertiesForKeys: nil
        ).filter { $0.pathExtension == "json" }
        XCTAssertGreaterThan(urls.count, 20, "The contract export should be here")

        var checked = 0
        for url in urls {
            guard case .object(let fields) = try JSONValue(data: try Data(contentsOf: url)),
                  case .object(let errors)? = fields["errors"]
            else { continue }
            for (status, body) in errors {
                let data = try JSONEncoder().encode(body)
                let decoded = try JSONDecoder.buddy.decode(ControlAPI.ErrorResponse.self, from: data)
                XCTAssertFalse(
                    decoded.error.isEmpty,
                    "\(url.lastPathComponent) \(status) has an empty message"
                )
                // And the mapping has somewhere to put it.
                let mapped = TransportError.from(
                    status: Int(status) ?? 0, body: data, path: "/x"
                )
                XCTAssertNotNil(mapped, "\(status) should map to an error")
                checked += 1
            }
        }
        XCTAssertGreaterThan(checked, 30, "Every route lists the errors it can answer")
    }

    /// A chat-scope device asking to load a model gets this, and it is not the same
    /// thing as "your token is wrong".
    func testTheScopeRefusalIsNotAnUnpairing() throws {
        let fields = try fixture("POST__load")
        let body = try JSONEncoder().encode(try XCTUnwrap(fields["errors"]?["403"]))
        let error = TransportError.from(status: 403, body: body, path: "/load")
        guard case .forbidden(let message)? = error else {
            return XCTFail("403 should be its own case, not unauthorized")
        }
        XCTAssertTrue(message.contains("chat only"))
        XCTAssertNotEqual(error, .unauthorized)
    }

    // MARK: - Requests this app builds

    func testRequestsEncodeTheWayTheMacReadsThem() throws {
        let load = ControlAPI.LoadRequest(modelID: "bonsai-2-27b", quantization: "PTQ1_0")
        let json = try JSONValue(data: JSONEncoder.buddy.encode(load))
        XCTAssertEqual(json["modelID"], .string("bonsai-2-27b"))
        XCTAssertNil(json["contextLength"], "Absent options must not be sent as null")
    }

    func testANewMessageCarriesContentNotATranscript() throws {
        let request = BuddyAPI.NewMessageRequest(
            content: "What is this?", images: ["data:image/jpeg;base64,AAA"], maxTokens: 2048
        )
        let json = try JSONValue(data: JSONEncoder.buddy.encode(request))
        XCTAssertEqual(json["content"], .string("What is this?"))
        XCTAssertEqual(json["images"]?[0], .string("data:image/jpeg;base64,AAA"))
        XCTAssertEqual(json["maxTokens"], .number(2048))
        XCTAssertNil(json["messages"], "The Mac has the history; this route takes one message")
    }

    func testAnEmptyImageListIsStillSent() throws {
        let request = ControlAPI.ChatRequest(messages: [.init(role: "user", content: "hi")])
        let json = try JSONValue(data: JSONEncoder.buddy.encode(request))
        XCTAssertEqual(json["messages"]?[0]?["images"], .array([]))
    }

    // MARK: - A failed load

    /// Every ending the Mac documents on `GET /status`, decoded and re-encoded whole.
    func testEveryFailedLoadTheMacDocumentsRoundTrips() throws {
        guard case .object(let variants)? = try fixture("GET__status")["responseVariants"] else {
            return XCTFail("GET /status documents no failed loads — refresh the contract")
        }
        var decoded: [String: ControlAPI.Status] = [:]
        for label in variants.keys {
            decoded[label] = try roundTrip(ControlAPI.Status.self, "GET__status", "responseVariants.\(label)")
        }
        XCTAssertGreaterThanOrEqual(decoded.count, 5)
        for (label, status) in decoded {
            XCTAssertFalse(status.state.contains("\n"), "\(label): state stays one line")
            XCTAssertNil(status.loadedModelID, label)
            if let failure = status.failure { XCTAssertFalse(failure.at.isEmpty, label) }
            XCTAssertTrue(
                status.failure != nil || status.interruptedLoads != nil,
                "\(label): a failure or a stopped load"
            )
        }

        let killed = try XCTUnwrap(decoded["after a failed load"]?.failure)
        XCTAssertEqual(killed.kind, .killed)
        XCTAssertEqual(killed.signal, 9)
        XCTAssertTrue(killed.detail?.contains("load_tensors") == true, "the log is the detail")
        XCTAssertEqual(killed.facts, "llama.cpp · signal 9")
        XCTAssertEqual(killed.modelID, "bonsai-2-27b", "whose load it was")

        // Replaced: no failure at all — the state line is the new load's, and the ending is
        // in `interruptedLoads` only.
        let replaced = try XCTUnwrap(decoded["after a load that was replaced"])
        XCTAssertNil(replaced.failure)
        let stopped = try XCTUnwrap(replaced.interruption(of: "bonsai-2-27b@Q4_K_M"))
        XCTAssertEqual(stopped.kind, .replaced)
        XCTAssertEqual(stopped.replacedBy, "qwen3-coder-30b")
        XCTAssertNil(replaced.interruption(of: "qwen3-coder-30b"), "not a model that was stopped")

        // Cancelled by an unload: both, for a phone from before `interruptedLoads`.
        let cancelled = try XCTUnwrap(decoded["after a load that was cancelled"])
        XCTAssertEqual(cancelled.failure?.kind, .cancelled)
        XCTAssertEqual(cancelled.interruption(of: "bonsai-2-27b")?.kind, .cancelled)
        XCTAssertEqual(decoded["after a load that never answered"]?.failure?.kind, .timedOut)

        // A device paired for chat is told the same failure without the runtime's log.
        let withheld = try XCTUnwrap(decoded["as a chat-scope device or a peer sees it"])
        XCTAssertNil(withheld.failure?.detail)
        XCTAssertEqual(withheld.state, decoded["after a failed load"]?.state)
    }

    func testAStopThisAppDoesNotKnowReadsAsCancelledAndAnOlderMacSendsNeither() throws {
        let json = Data(#"{"state":"Not loaded","expertStreaming":false,"interruptedLoads":[{"modelID":"m","reason":"evicted","at":"2026-09-19T11:04:38Z"}]}"#.utf8)
        let status = try JSONDecoder.buddy.decode(ControlAPI.Status.self, from: json)
        XCTAssertEqual(status.interruption(of: "m")?.kind, .cancelled)
        let older = Data(#"{"state":"x","expertStreaming":false,"failure":{"reason":"killed","wasReplaced":false,"at":"2026-09-19T11:04:38Z"}}"#.utf8)
        let old = try JSONDecoder.buddy.decode(ControlAPI.Status.self, from: older)
        XCTAssertNil(old.interruptedLoads)
        XCTAssertNil(old.failure?.modelID)
    }

    /// A load another load or an unload stopped inside the Mac's patience: a 409, in words.
    func testALoadStoppedBeforeItFinishedIsAConflictTheMacExplains() throws {
        for label in ["replaced by another load before it finished", "stopped by an unload before it finished"] {
            let body = try JSONEncoder().encode(
                try XCTUnwrap(try fixture("POST__load")["errorVariants"]?["409"]?[label])
            )
            guard case .conflict(let sentence)? = TransportError.from(status: 409, body: body, path: "/load") else {
                return XCTFail("\(label) should be a conflict")
            }
            XCTAssertTrue(sentence.hasPrefix("Bonsai 2 27B was not loaded:"), label)
        }
    }

    /// Render and queue results name their files for a device, never where they sit.
    func testQueueItemsNameTheirFilesNotWhereTheySit() throws {
        for name in ["GET__video_queue", "POST__video_queue", "POST__video_queue_control"] {
            for item in try roundTrip(ControlAPI.VideoQueueView.self, name).items {
                for value in [item.outputDirectory] + [item.file].compactMap({ $0 }) {
                    XCTAssertFalse(value.contains("/") || value.hasPrefix("~"), "\(name): \(value) is a path")
                }
            }
        }
    }

    func testAFailureReasonThisAppDoesNotKnowReadsAsExited() throws {
        let json = Data(#"{"state":"The runtime ran out of cheese.","expertStreaming":false,"failure":{"reason":"outOfCheese","wasReplaced":false,"at":"2026-09-19T11:04:38Z"}}"#.utf8)
        let failure = try XCTUnwrap(try JSONDecoder.buddy.decode(ControlAPI.Status.self, from: json).failure)
        XCTAssertEqual(failure.kind, .exited)
        XCTAssertNil(failure.detail)
        XCTAssertNil(failure.facts, "nothing to say about how it ended")
    }

    // MARK: - Decoding is forgiving where the Mac says it may be

    func testAStatusFromAnOlderMacStillDecodes() throws {
        let json = Data(#"{"state":"Not loaded","expertStreaming":false}"#.utf8)
        let status = try JSONDecoder.buddy.decode(ControlAPI.Status.self, from: json)
        XCTAssertFalse(status.hasLoadedModel)
        XCTAssertNil(status.failure, "a Mac from before failures were structured sends none")
    }

    func testAPairResponseWithoutAScopeMeansFull() throws {
        let json = Data(#"{"deviceID":"1","token":"t","macName":"Mac","port":8788}"#.utf8)
        let paired = try JSONDecoder.buddy.decode(BuddyAPI.PairResponse.self, from: json)
        XCTAssertNil(paired.scope)
        XCTAssertEqual(BuddyAPI.DeviceScope(wire: paired.scope), .full)
    }

    func testConversationTimestampsDecodeBothISOSpellings() throws {
        let withFraction = Data(#"{"id":"1","title":"t","updatedAt":"2026-09-18T10:11:12.345Z","messageCount":2}"#.utf8)
        let plain = Data(#"{"id":"1","title":"t","updatedAt":"2026-09-18T10:11:12Z","messageCount":2}"#.utf8)
        XCTAssertNoThrow(try JSONDecoder.buddy.decode(BuddyAPI.ConversationSummary.self, from: withFraction))
        XCTAssertNoThrow(try JSONDecoder.buddy.decode(BuddyAPI.ConversationSummary.self, from: plain))
    }
}
