#!/usr/bin/env bash
# Re-export the control API contract from a silicon-optimizer checkout.
#
# The fixtures in this directory are generated by that repository's own
# ContractExportTests, not captured by hand: they are the shapes its wire types
# encode, so a change there fails a test here before it fails a person holding a
# phone. Both apps read these same files.
#
#   ./contract/refresh.sh                      # uses the default checkout below
#   ./contract/refresh.sh ~/src/silicon-optimizer
#   ./contract/refresh.sh ~/src/silicon-optimizer feat/buddy-remote-access
#
# The Mac checkout is never modified: the export runs in a detached worktree in
# a temporary directory, which is removed afterwards.
set -euo pipefail

checkout="${1:-/Volumes/T9/Apple Silicon AI Optimizer}"
ref="${2:-origin/feat/buddy-remote-access}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -d "$checkout/.git" ]; then
    echo "Not a git checkout: $checkout" >&2
    exit 1
fi

worktree="$(mktemp -d)/silicon-optimizer"
export_dir="$(mktemp -d)/contract"
cleanup() {
    git -C "$checkout" worktree remove --force "$worktree" >/dev/null 2>&1 || true
    rm -rf "$(dirname "$worktree")" "$(dirname "$export_dir")"
}
trap cleanup EXIT

echo "Fetching $ref…"
git -C "$checkout" fetch --quiet origin
git -C "$checkout" worktree add --detach "$worktree" "$ref" >/dev/null

echo "Exporting…"
mkdir -p "$export_dir"
( cd "$worktree" && SILICON_EXPORT_CONTRACT="$export_dir" swift test --filter ContractExportTests >/dev/null )

count=$(ls "$export_dir" | wc -l | tr -d ' ')
if [ "$count" -lt 2 ]; then
    echo "The export produced nothing. Has ContractExportTests moved?" >&2
    exit 1
fi

rm -f "$here"/*.json "$here"/routes.md
cp "$export_dir"/* "$here"/
echo "Wrote $count files to $here. Run both test suites."
