#!/usr/bin/env bash
# Re-export the control API contract from a silicon-optimizer checkout.
#
# The fixtures in this directory are generated by that repository's own
# ContractExportTests, not captured by hand: they are the shapes its wire types
# encode, so a change there fails a test here before it fails a person holding a
# phone. Both apps read these same files.
#
#   ./contract/refresh.sh ~/src/silicon-optimizer
#   ./contract/refresh.sh ~/src/silicon-optimizer origin/some-branch
#   SILICON_OPTIMIZER_CHECKOUT=~/src/silicon-optimizer ./contract/refresh.sh
#
# The Mac checkout is never modified: the export runs in a detached worktree in
# a temporary directory, which is removed afterwards.
set -euo pipefail

checkout="${1:-${SILICON_OPTIMIZER_CHECKOUT:-}}"
ref="${2:-origin/main}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# There is no default: where somebody keeps their clone is theirs to say, and a
# guess would be one person's disk written into everybody's script.
if [ -z "$checkout" ]; then
    echo "Which silicon-optimizer clone? Pass its path, or set SILICON_OPTIMIZER_CHECKOUT:" >&2
    echo "  ./contract/refresh.sh ~/src/silicon-optimizer [ref, default origin/main]" >&2
    exit 2
fi
# `-e`, not `-d`: in a linked worktree `.git` is a file.
if [ ! -e "$checkout/.git" ]; then
    echo "Not a git checkout: $checkout" >&2
    exit 1
fi

# The export builds the Mac app's test target, which is gigabytes. macOS's `mktemp -d`
# ignores TMPDIR, so the scratch folders are made under it explicitly: set TMPDIR to a
# roomy drive and the whole build lands there.
scratch="${TMPDIR:-/tmp}"
worktree="$(mktemp -d "${scratch%/}/contract-refresh.XXXXXX")/silicon-optimizer"
export_dir="$(mktemp -d "${scratch%/}/contract-export.XXXXXX")/contract"
cleanup() {
    git -C "$checkout" worktree remove --force "$worktree" >/dev/null 2>&1 || true
    rm -rf "$(dirname "$worktree")" "$(dirname "$export_dir")"
}
trap cleanup EXIT

echo "Fetching $ref…"
git -C "$checkout" fetch --quiet origin
git -C "$checkout" worktree add --detach "$worktree" "$ref" >/dev/null

echo "Exporting from $ref ($(git -C "$worktree" rev-parse --short HEAD))…"
mkdir -p "$export_dir"
( cd "$worktree" && SILICON_EXPORT_CONTRACT="$export_dir" swift test --filter ContractExportTests >/dev/null )

count=$(ls "$export_dir" | wc -l | tr -d ' ')
if [ "$count" -lt 2 ]; then
    echo "The export produced nothing. Has ContractExportTests moved?" >&2
    exit 1
fi

rm -f "$here"/*.json "$here"/routes.md
cp "$export_dir"/* "$here"/
echo "Wrote $count files to $here. Run both test suites."
