package dev.siliconoptimizer.buddy

import dev.siliconoptimizer.buddy.chat.SendLimits
import dev.siliconoptimizer.buddy.transport.AgentApprovalDecision
import dev.siliconoptimizer.buddy.transport.AgentApprovalResult
import dev.siliconoptimizer.buddy.transport.AgentEvent
import dev.siliconoptimizer.buddy.transport.AgentMessageAccepted
import dev.siliconoptimizer.buddy.transport.AgentMessageRequest
import dev.siliconoptimizer.buddy.transport.AgentScreening
import dev.siliconoptimizer.buddy.transport.ResyncEvent
import dev.siliconoptimizer.buddy.transport.AgentSessionDetail
import dev.siliconoptimizer.buddy.transport.AgentSessionList
import dev.siliconoptimizer.buddy.transport.AgentSessionSummary
import dev.siliconoptimizer.buddy.transport.CatalogModel
import dev.siliconoptimizer.buddy.transport.ChatMessageWire
import dev.siliconoptimizer.buddy.transport.ChatMetrics
import dev.siliconoptimizer.buddy.transport.ChatRequest
import dev.siliconoptimizer.buddy.transport.ChatResponse
import dev.siliconoptimizer.buddy.transport.ConversationDetail
import dev.siliconoptimizer.buddy.transport.ConversationSummary
import dev.siliconoptimizer.buddy.transport.DeviceScope
import dev.siliconoptimizer.buddy.transport.DownloadProgress
import dev.siliconoptimizer.buddy.transport.ErrorResponse
import dev.siliconoptimizer.buddy.transport.Health
import dev.siliconoptimizer.buddy.transport.Heartbeat
import dev.siliconoptimizer.buddy.transport.ImageModel
import dev.siliconoptimizer.buddy.transport.ImagePlan
import dev.siliconoptimizer.buddy.transport.ImageRequest
import dev.siliconoptimizer.buddy.transport.ImageResponse
import dev.siliconoptimizer.buddy.transport.InstalledModel
import dev.siliconoptimizer.buddy.transport.JevView
import dev.siliconoptimizer.buddy.transport.JobProgress
import dev.siliconoptimizer.buddy.transport.LoadFailure
import dev.siliconoptimizer.buddy.transport.LoadRequest
import dev.siliconoptimizer.buddy.transport.MeshModel
import dev.siliconoptimizer.buddy.transport.MeshPlan
import dev.siliconoptimizer.buddy.transport.MeshRequest
import dev.siliconoptimizer.buddy.transport.MeshResponse
import dev.siliconoptimizer.buddy.transport.Metrics
import dev.siliconoptimizer.buddy.transport.NewConversation
import dev.siliconoptimizer.buddy.transport.NewMessageRequest
import dev.siliconoptimizer.buddy.transport.NodeAdvertisement
import dev.siliconoptimizer.buddy.transport.PairRequest
import dev.siliconoptimizer.buddy.transport.PairResponse
import dev.siliconoptimizer.buddy.transport.PairedDevice
import dev.siliconoptimizer.buddy.transport.PeerNodeStatus
import dev.siliconoptimizer.buddy.transport.PhoneModel
import dev.siliconoptimizer.buddy.transport.PhoneModelList
import dev.siliconoptimizer.buddy.transport.Plan
import dev.siliconoptimizer.buddy.transport.PlanRequest
import dev.siliconoptimizer.buddy.transport.Profile
import dev.siliconoptimizer.buddy.transport.Status
import dev.siliconoptimizer.buddy.transport.StatusMessage
import dev.siliconoptimizer.buddy.transport.SwarmView
import dev.siliconoptimizer.buddy.transport.TokenEvent
import dev.siliconoptimizer.buddy.transport.TransportError
import dev.siliconoptimizer.buddy.transport.UploadResponse
import dev.siliconoptimizer.buddy.transport.Uploads
import dev.siliconoptimizer.buddy.transport.VideoGenerateRequest
import dev.siliconoptimizer.buddy.transport.VideoModel
import dev.siliconoptimizer.buddy.transport.VideoQueueControlRequest
import dev.siliconoptimizer.buddy.transport.VideoQueueRequest
import dev.siliconoptimizer.buddy.transport.VideoQueueView
import dev.siliconoptimizer.buddy.transport.VideoResponse
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.doubleOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The mirrored types, checked against the Mac's own export.
 *
 * `contract/` is generated by silicon-optimizer's ContractExportTests — the shapes its
 * wire types actually encode. Each file holds a route: its request, its response, the
 * events it can send and the errors it can answer. The round trip is the part that
 * matters: decode, re-encode, compare the JSON. A field this app forgot to mirror
 * disappears in the re-encode, so the comparison fails.
 */
class ContractTest {

    private val json = Json {
        ignoreUnknownKeys = true
        explicitNulls = false
        encodeDefaults = true
    }

    private fun fixture(name: String): JsonObject {
        val text = javaClass.classLoader?.getResourceAsStream("$name.json")?.bufferedReader()
            ?.readText() ?: error("Missing fixture $name.json — run contract/refresh.sh")
        return Json.parseToJsonElement(text) as JsonObject
    }

    private fun part(name: String, part: String): JsonElement {
        val fields = fixture(name)
        return when {
            part.startsWith("requests.") ->
                (fields["requests"] as JsonObject).getValue(part.removePrefix("requests."))
            part.startsWith("events.") ->
                (fields["events"] as JsonObject).getValue(part.removePrefix("events."))
            part.startsWith("errors.") ->
                (fields["errors"] as JsonObject).getValue(part.removePrefix("errors."))
            // `eventVariants.agent.approval answered`: one named variant of one event.
            part.startsWith("eventVariants.") -> {
                val (event, variant) = part.removePrefix("eventVariants.").split(".", limit = 2)
                ((fields["eventVariants"] as JsonObject).getValue(event) as JsonObject).getValue(variant)
            }
            // `responseVariants.still loading`: another answer the same route can give.
            part.startsWith("responseVariants.") ->
                (fields["responseVariants"] as JsonObject).getValue(part.removePrefix("responseVariants."))
            // `errorVariants.409.still screening`: one more refusal a status can carry.
            part.startsWith("errorVariants.") -> {
                val (status, label) = part.removePrefix("errorVariants.").split(".", limit = 2)
                ((fields["errorVariants"] as JsonObject).getValue(status) as JsonObject).getValue(label)
            }
            else -> fields.getValue(part)
        }
    }

    private inline fun <reified T> roundTrip(name: String, part: String = "response"): T {
        val piece = part(name, part)
        val decoded = json.decodeFromString<T>(piece.toString())
        val reencoded = json.encodeToString(decoded)
        assertEquals(
            "$name.$part changed shape on a round trip",
            decoded,
            json.decodeFromString<T>(reencoded),
        )
        val differences = difference(strip(piece), strip(Json.parseToJsonElement(reencoded)))
        assertTrue(
            "$name.$part lost or changed fields on a round trip:\n" +
                differences.joinToString("\n"),
            differences.isEmpty(),
        )
        return decoded
    }

    private fun strip(element: JsonElement): JsonElement = when (element) {
        is JsonObject -> JsonObject(
            element.filterValues { it !is JsonNull }.mapValues { strip(it.value) },
        )
        is JsonArray -> JsonArray(element.map { strip(it) })
        else -> element
    }

    private fun difference(mine: JsonElement, theirs: JsonElement, path: String = ""): List<String> =
        when {
            mine is JsonObject && theirs is JsonObject ->
                (mine.keys + theirs.keys).sorted().flatMap { key ->
                    val childPath = if (path.isEmpty()) key else "$path.$key"
                    val a = mine[key]
                    val b = theirs[key]
                    when {
                        a == null -> listOf("+ $childPath appeared after the round trip")
                        b == null -> listOf("- $childPath was lost — is it mirrored?")
                        else -> difference(a, b, childPath)
                    }
                }
            mine is JsonArray && theirs is JsonArray ->
                if (mine.size != theirs.size) {
                    listOf("$path has ${mine.size} items, round trip has ${theirs.size}")
                } else {
                    mine.indices.flatMap { difference(mine[it], theirs[it], "$path[$it]") }
                }
            mine is JsonPrimitive && theirs is JsonPrimitive -> {
                val a = mine.doubleOrNull
                val b = theirs.doubleOrNull
                val same = if (a != null && b != null) a == b else mine.content == theirs.content
                if (same) emptyList() else listOf("$path: $mine != $theirs")
            }
            else -> if (mine == theirs) emptyList() else listOf("$path: $mine != $theirs")
        }

    // MARK: - The routes this app calls today

    @Test fun health() { assertEquals("ok", roundTrip<Health>("GET__health").status) }

    @Test fun status() { assertTrue(roundTrip<Status>("GET__status").hasLoadedModel) }

    @Test fun profile() { assertTrue(roundTrip<Profile>("GET__profile").totalMemoryBytes > 0) }

    @Test fun metrics() { assertTrue(roundTrip<Metrics>("GET__metrics").memoryTotalBytes > 0) }

    @Test fun installed() {
        assertTrue(roundTrip<List<InstalledModel>>("GET__installed").isNotEmpty())
    }

    @Test fun catalog() {
        assertTrue(roundTrip<List<CatalogModel>>("GET__catalog").any { it.recommendation != null })
    }

    @Test fun recommend() { roundTrip<CatalogModel>("GET__recommend") }

    @Test fun swarm() { roundTrip<SwarmView>("GET__swarm") }

    @Test fun nodeAdvertisement() {
        assertTrue(roundTrip<NodeAdvertisement>("GET__v1_node").profile.memoryGB > 0)
    }

    @Test fun videoModels() { roundTrip<List<VideoModel>>("GET__video_models") }

    @Test fun videoQueue() { roundTrip<VideoQueueView>("GET__video_queue") }

    @Test fun imageModels() { roundTrip<List<ImageModel>>("GET__image_models") }

    @Test fun meshModels() { roundTrip<List<MeshModel>>("GET__mesh_models") }

    @Test fun chat() {
        roundTrip<ChatRequest>("POST__chat", "request")
        assertTrue(roundTrip<ChatResponse>("POST__chat").content.isNotEmpty())
    }

    @Test fun loadAndInstall() {
        roundTrip<LoadRequest>("POST__load", "request")
        roundTrip<Status>("POST__load")
        // A load slower than the request's patience: the live status, nothing resident yet,
        // and nothing claimed to have failed — the load carries on on the Mac.
        val stillLoading = roundTrip<Status>("POST__load", "responseVariants.still loading")
        assertNull(stillLoading.loadedModelID)
        assertNull(stillLoading.failure)
        // A second load while one runs is refused, and the phone is told it as a conflict.
        val refusal = TransportError.from(409, part("POST__load", "errors.409").toString(), "/load")
        assertTrue(refusal is TransportError.Conflict)
        assertTrue(refusal!!.message!!.contains("Nothing was changed"))
        roundTrip<LoadRequest>("POST__install", "request")
        roundTrip<StatusMessage>("POST__install")
        roundTrip<StatusMessage>("POST__unload")
    }

    @Test fun plan() {
        roundTrip<PlanRequest>("POST__plan", "request")
        roundTrip<Plan>("POST__plan")
    }

    // MARK: - The M0 routes

    @Test fun pairing() {
        roundTrip<PairRequest>("POST__buddy_pair", "request")
        val paired = roundTrip<PairResponse>("POST__buddy_pair")
        assertEquals(DeviceScope.Full, DeviceScope.from(paired.scope))
    }

    @Test fun pairedDevices() {
        assertEquals("full", roundTrip<List<PairedDevice>>("GET__buddy_devices").first().scope)
        roundTrip<StatusMessage>("DELETE__buddy_devices__id_")
    }

    @Test fun conversations() {
        assertEquals(2, roundTrip<List<ConversationSummary>>("GET__conversations").first().messageCount)
        roundTrip<NewConversation>("POST__conversations", "request")
        roundTrip<ConversationSummary>("POST__conversations")
    }

    @Test fun conversationDetail() {
        val detail = roundTrip<ConversationDetail>("GET__conversations__id_")
        assertFalse(detail.isGenerating)
        assertEquals(2, detail.messages.size)
    }

    /** The route this app got wrong once: it takes one message, not a transcript. */
    @Test fun sendingAMessageToAConversation() {
        val request = roundTrip<NewMessageRequest>("POST__conversations__id__messages", "request")
        assertTrue(request.content.isNotEmpty())
        assertEquals(emptyList<String>(), request.images)
    }

    @Test fun chatStreamEvents() {
        roundTrip<TokenEvent>("POST__chat_stream", "events.token")
        roundTrip<TokenEvent>("POST__chat_stream", "events.reasoning")
        assertNotNull(roundTrip<ChatMetrics>("POST__chat_stream", "events.finished").timeToFirstToken)
        roundTrip<ErrorResponse>("POST__chat_stream", "events.error")
    }

    @Test fun serverEvents() {
        roundTrip<Status>("GET__events", "events.status")
        assertEquals(0.42, roundTrip<DownloadProgress>("GET__events", "events.download").progress)
        assertEquals("running", roundTrip<JobProgress>("GET__events", "events.job").status)
        roundTrip<Heartbeat>("GET__events", "events.heartbeat")
    }


    // MARK: - M5: the models the Mac keeps for this phone

    @Test
    fun `the phone's models are pinned to exact bytes, with the Mac's copy and a real phone's numbers`() {
        val list = roundTrip<PhoneModelList>("GET__ondevice_models")
        val qwen = list.models.single { it.isDefault }
        assertEquals("qwen3.5-2b-q4_0", qwen.id)
        assertEquals(1_296_764_000L, qwen.sizeBytes)
        assertEquals("91c102fc9a86de80e427057ee938e1e34fcaf3bba956b7296e252406e05f36f6", qwen.sha256)
        assertEquals("7d26695454df6de5fbcce2e58681e62dae06ce43", qwen.source.commit)
        assertTrue(qwen.onMac.isReady)
        // What the phone runs it with: the Mac's numbers from the owner's own phone.
        assertEquals(6, qwen.recommended.threadsPrompt)
        assertEquals(4, qwen.recommended.threadsGenerate)
        assertEquals(4096, qwen.recommended.contextLength)
        // The weights with no margin — Android can page them back from the file — plus the
        // rest of the measured peak grown to 4,096 tokens, plus a quarter.
        assertEquals(3_100_000_000L, qwen.recommended.minFreeMemoryBytes)
        assertFalse(qwen.recommended.thinking)
        assertEquals(2.5, qwen.measured!!.secondsToFirstWord300, 1e-9)
        assertNull("not measured is not claimed", qwen.measured!!.sustainedTokensPerSecond)
        // The Mac lists more than one alternative now; each is found by its id.
        val gemma = list.models.single { it.id == "gemma-4-e2b-q4_0" }
        assertFalse(gemma.isDefault)
        assertEquals("only one default", 1, list.models.count { it.isDefault })
        assertTrue(gemma.slowerOnPhone)
        assertEquals(4_700_000_000L, gemma.recommended.minFreeMemoryBytes)
        assertEquals(7.5, gemma.measured!!.sustainedTokensPerSecond!!, 1e-9)
        assertTrue(gemma.measured!!.sustainedMeasured)
        assertTrue(gemma.onMac.isFailed)
        assertEquals("network", gemma.onMac.failure)
        assertEquals(listOf("full"), scopes("GET__ondevice_models"))
    }

    @Test
    fun `prepare and delete answer the entry itself`() {
        val prepared = roundTrip<PhoneModel>("POST__ondevice_models__id__prepare")
        assertEquals("ondevice:${prepared.id}", prepared.downloadEventID)
        roundTrip<PhoneModel>("DELETE__ondevice_models__id_")
        assertEquals(JsonNull, fixture("POST__ondevice_models__id__prepare")["request"])
        for (name in listOf("POST__ondevice_models__id__prepare", "DELETE__ondevice_models__id_", "GET__ondevice_models__id__file")) {
            assertEquals(listOf("full"), scopes(name))
        }
    }

    @Test
    fun `the file and prepare refusals reach the phone as cases it can act on`() {
        val file = "GET__ondevice_models__id__file"
        assertEquals(JsonNull, fixture(file)["response"])
        assertTrue("409: not ready on the Mac yet", TransportError.from(409, part(file, "errors.409").toString(), "/x") is TransportError.Conflict)
        assertTrue(TransportError.from(416, part(file, "errors.416").toString(), "/x") is TransportError.RangeNotSatisfiable)
        val missing = TransportError.from(503, part(file, "errors.503").toString(), "/x")
        assertTrue("503: the Mac's library drive is gone", missing is TransportError.Unavailable)
        assertTrue("and the Mac's sentence names it", missing!!.message!!.contains("is not connected"))
        val prepare = "POST__ondevice_models__id__prepare"
        assertTrue("507: no room on the Mac", TransportError.from(507, part(prepare, "errors.507").toString(), "/x") is TransportError.InsufficientStorage)
        assertTrue(TransportError.from(503, part(prepare, "errors.503").toString(), "/x") is TransportError.Unavailable)
        assertTrue(TransportError.from(403, part(prepare, "errors.403").toString(), "/x") is TransportError.Forbidden)
        assertTrue(
            TransportError.from(403, part(prepare, "errorVariants.403.swarm").toString(), "/x")!!.message!!
                .contains("swarm node may not"),
        )
    }

    @Test
    fun `the Mac fetching a phone model arrives as download frames with a stage`() {
        val fetching = roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model")
        assertTrue(fetching.isPhoneModel)
        assertEquals("gemma-4-e2b-q4_0", fetching.phoneModelID)
        assertEquals("fetching", fetching.stage)
        assertEquals("checking", roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model checking").stage)
        assertEquals("moving", roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model moving").stage)
        val ready = roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model ready")
        assertNull("done has no stage", ready.stage)
        assertEquals(1.0, ready.progress!!, 1e-9)
        val failed = roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model failed")
        assertTrue(failed.error!!.contains("checksum"))
        assertEquals(
            "Removed from the Mac before it finished.",
            roundTrip<DownloadProgress>("GET__events", "eventVariants.download.phone model removed").error,
        )
        assertFalse("the Mac's own downloads are not the phone's", roundTrip<DownloadProgress>("GET__events", "events.download").isPhoneModel)
    }

    private fun scopes(name: String): List<String> =
        (fixture(name)["scopes"] as JsonArray).map { (it as JsonPrimitive).content }

    // MARK: - The M3 routes: starting work, and what comes back

    @Test
    fun `queueing a clip`() {
        val request = roundTrip<VideoQueueRequest>("POST__video_queue", "request")
        assertEquals(1, request.prompts.size)
        assertEquals(2, request.variations)
        roundTrip<VideoQueueView>("POST__video_queue")
    }

    /** Six verbs, each with a fixture of its own now, and no seventh. */
    @Test
    fun `controlling the queue`() {
        val fixture = fixture("POST__video_queue_control")
        val requests = fixture.getValue("requests") as JsonObject
        assertEquals(
            setOf("pause", "resume", "retry", "remove", "stop_following", "clear_finished"),
            requests.keys,
        )
        for (action in requests.keys) {
            val sent = roundTrip<VideoQueueControlRequest>(
                "POST__video_queue_control", "requests.$action",
            )
            assertEquals(action, sent.action)
            if (action in VideoQueueControlRequest.NEEDS_ID) {
                assertNotNull("$action names the item it is about", sent.id)
            } else {
                assertNull("$action is about the queue, not an item", sent.id)
            }
        }
        assertTrue(
            "retry is the one that has to be meant",
            roundTrip<VideoQueueControlRequest>(
                "POST__video_queue_control", "requests.retry",
            ).confirmNewRender == true,
        )
        roundTrip<VideoQueueView>("POST__video_queue_control")
    }

    @Test
    fun `a lane says what it takes`() {
        val lanes = roundTrip<List<VideoModel>>("GET__video_models")
        val h3 = lanes.first()
        assertEquals(listOf("480p", "720p", "1080p"), h3.supportedResolutions)
        assertTrue(h3.supportsNegativePrompt == true)
        assertTrue(h3.supportedParameters.orEmpty().contains("negative_prompt"))
    }

    @Test
    fun `a queue item carries its reason, its file and the id that fetches it`() {
        val queue = roundTrip<VideoQueueView>("GET__video_queue")
        assertNotNull("the Mac's word about the queue itself", queue.message)
        val done = queue.items.first { it.status == "completed" }
        assertNotNull(done.file)
        assertNotNull(done.mediaID)
        assertNotNull("a poster a chat-scope device may fetch", done.thumbnailMediaID)
        assertNotNull("why the Mac chose what it chose", done.detail)
        val failed = queue.items.first { it.status == "failed" }
        assertNotNull(failed.error)
        assertTrue(failed.uncertainSubmission)
        assertNotNull(queue.items.first().negativePrompt)
    }

    @Test
    fun `a job event carries the stage and the reason the queue used to hold`() {
        val job = roundTrip<JobProgress>("GET__events", "events.job")
        assertEquals("video-denoise 18/30", job.stage)
        assertEquals("running", job.status)
    }

    @Test
    fun `sending a picture, and fetching a result back`() {
        val upload = roundTrip<UploadResponse>("POST__uploads")
        assertTrue(upload.uploadID.isNotEmpty())
        assertEquals("/media/${upload.mediaID}", upload.mediaURL)
        assertEquals("image/jpeg", upload.contentType)
        // The ceiling this app refuses at is the one the Mac documents.
        val tooLarge = (part("POST__uploads", "errors.413") as JsonObject)
            .getValue("error").toString()
        assertTrue(tooLarge.contains(Uploads.MAXIMUM_BYTES.toString()))
        // `GET /media/{id}` answers bytes, so there is no response type to mirror —
        // only the scopes, which decide what this app offers to whom.
        assertEquals(listOf("full", "chat"), fixture("GET__media__id_")["scopes"].toString()
            .removeSurrounding("[", "]").split(",").map { it.trim().removeSurrounding("\"") })
    }

    @Test
    fun `a peer asked directly says what the poll cannot`() {
        val peer = roundTrip<PeerNodeStatus>("GET__swarm_peers__name__status")
        assertEquals("silicon-node", peer.name)
        assertEquals("NVIDIA GeForce RTX 3090 Ti", peer.hardware)
        assertNotNull(peer.gguf)
        assertEquals("bonsai-27b-v3.lora.gguf", peer.gguf!!.adapter)
        assertTrue(peer.gguf!!.installedModels.isNotEmpty())
        assertEquals(listOf("full"), fixture("GET__swarm_peers__name__status")["scopes"]
            .toString().removeSurrounding("[", "]").split(",")
            .map { it.trim().removeSurrounding("\"") })
    }

    @Test
    fun `rendering one clip and waiting`() {
        val request = roundTrip<VideoGenerateRequest>("POST__video_generate", "request")
        assertEquals("hailuo-h3", request.modelID)
        assertEquals(5, request.seconds)
        assertEquals("what a device may name a picture with", null, request.imagePath)
        assertNotNull(request.uploadID)
        assertNotNull(request.negativePrompt)
        val clip = roundTrip<VideoResponse>("POST__video_generate")
        assertTrue(clip.file.startsWith("/"))
        assertNotNull("and now the phone can fetch it", clip.mediaID)
        assertNotNull(clip.thumbnailMediaID)
    }

    @Test
    fun `planning and generating an image take the same body`() {
        val planned = roundTrip<ImageRequest>("POST__image_plan", "request")
        val generated = roundTrip<ImageRequest>("POST__image_generate", "request")
        assertEquals(planned, generated)
        assertEquals(1024, roundTrip<ImagePlan>("POST__image_plan").width)
        val image = roundTrip<ImageResponse>("POST__image_generate")
        assertTrue(image.path.startsWith("/"))
        assertNotNull(image.peakMemoryBytes)
        assertNotNull(image.mediaID)
    }

    @Test
    fun `a mesh is asked for by an id, and comes back as one`() {
        val request = roundTrip<MeshRequest>("POST__mesh_plan", "request")
        assertNotNull("what a device sends instead of a path", request.uploadID)
        assertEquals(request, roundTrip<MeshRequest>("POST__mesh_generate", "request"))
        assertFalse(roundTrip<MeshPlan>("POST__mesh_plan").isRemote)
        val mesh = roundTrip<MeshResponse>("POST__mesh_generate")
        assertTrue(mesh.glbPath!!.startsWith("/"))
        assertNotNull(mesh.mediaID)
        assertNotNull("the OBJ has an id of its own", mesh.objMediaID)
    }

    /** Read for one fact: whether this Mac would pick the model for a media request. */
    @Test
    fun `jev says whether the Mac routes media itself`() {
        val jev = roundTrip<JevView>("GET__jev")
        assertTrue(jev.enabled)
        assertFalse("The fixture's Mac has the router built but switched off", jev.routesMedia)
        assertFalse(jev.advertisesMediaRouting)
        assertNotNull(jev.features.firstOrNull { it.id == JevView.MEDIA_ROUTING })
    }

    // MARK: - The M4 routes: the Mac's agent sessions

    @Test
    fun `the session list carries both engines, stopped ones included`() {
        val list = roundTrip<AgentSessionList>("GET__agent_sessions")
        assertEquals(listOf("codex", "pi"), list.sessions.map { it.engine })
        val codex = list.sessions.first()
        assertTrue(codex.turnActive)
        assertEquals(1, codex.pendingApprovals)
        assertEquals(2, codex.modelChoices.size)
        assertNotNull("Codex mints a thread id", codex.threadID)
        assertEquals(AgentSessionSummary.APPROVALS_SCREENED, codex.approvalMode)
        assertEquals("workspace-write", codex.sandbox)
        assertTrue("never the home folder's absolute path", codex.cwd!!.startsWith("~/"))
        val pi = list.sessions.last()
        assertNull("Pi has none to give", pi.threadID)
        assertEquals("stopped", pi.state)
        assertTrue("Pi with the guardrail off asks nobody", pi.runsWithoutAsking)
        assertEquals(AgentSessionSummary.SANDBOX_NONE, pi.sandbox)
        assertEquals("a stopped engine is asking nobody anything", 0, pi.pendingApprovals)
        assertTrue("each transcript has its own epoch", codex.epoch != pi.epoch)
    }

    @Test
    fun `a session carries its transcript, what is waiting, and the watermark`() {
        val detail = roundTrip<AgentSessionDetail>("GET__agent_sessions__engine_")
        assertTrue(detail.complete)
        assertEquals(41L, detail.seq)
        assertEquals("the cursor's two halves agree", detail.session.epoch, detail.epoch)
        assertEquals(0, detail.omitted)
        assertEquals(
            listOf("user", "reasoning", "assistant", "command", "fileChange"),
            detail.items.map { it.kind },
        )
        val command = detail.items.first { it.kind == "command" }
        assertNotNull("a command keeps what it printed apart", command.output)
        assertEquals("completed", command.status)
        assertEquals("only the tail of a long log travels, and it says so", true, command.truncated)
        assertEquals("the sending row carries the model it was sent with", "local/qwen3-coder-30b", detail.items.first().model)
        val waiting = detail.approvals.single()
        assertEquals("command", waiting.kind)
        assertEquals("rm -rf .build", waiting.summary)
        assertNotNull(waiting.reason)
        assertEquals("a card carries the guardrail's verdict", AgentScreening.CONFIRM, waiting.screening.verdict)
        assertTrue(waiting.screening.summary.startsWith("Jev"))
    }

    @Test
    fun `the verbs answer the session's summary`() {
        assertEquals("running", roundTrip<AgentSessionSummary>("POST__agent_sessions__engine__start").state)
        assertEquals(0, roundTrip<AgentSessionSummary>("POST__agent_sessions__engine__new").itemCount)
        roundTrip<AgentSessionSummary>("POST__agent_sessions__engine__interrupt")
        assertEquals("stopped", roundTrip<AgentSessionSummary>("DELETE__agent_sessions__engine_").state)
        for (name in listOf(
            "POST__agent_sessions__engine__start", "POST__agent_sessions__engine__new",
            "POST__agent_sessions__engine__interrupt", "DELETE__agent_sessions__engine_",
        )) {
            assertEquals("$name takes no body", JsonNull, fixture(name)["request"])
        }
    }

    @Test
    fun `sending a turn is text and a model, and answers the row it became`() {
        val request = roundTrip<AgentMessageRequest>("POST__agent_sessions__engine__messages", "request")
        assertTrue(request.text.isNotBlank())
        assertEquals("local/qwen3-coder-30b", request.model)
        assertTrue(roundTrip<AgentMessageAccepted>("POST__agent_sessions__engine__messages").itemID.isNotEmpty())
    }

    @Test
    fun `answering an approval is accept or decline, and says how it was applied`() {
        val request = roundTrip<AgentApprovalDecision>("POST__agent_sessions__engine__approvals__id_", "request")
        assertEquals(AgentApprovalDecision.ACCEPT, request.decision)
        val result = roundTrip<AgentApprovalResult>("POST__agent_sessions__engine__approvals__id_")
        assertEquals("accepted", result.decision)
        assertEquals(0, result.session.pendingApprovals)
    }

    /** The four kinds of `agent` frame, and the answered form of an approval. */
    @Test
    fun `agent frames on the event stream`() {
        val item = roundTrip<AgentEvent>("GET__events", "events.agent")
        assertEquals(AgentEvent.ITEM, item.kind)
        assertNotNull(item.item)
        assertEquals("running", roundTrip<AgentEvent>("GET__events", "eventVariants.agent.state").state)
        assertEquals(true, roundTrip<AgentEvent>("GET__events", "eventVariants.agent.turn").turnActive)
        val asked = roundTrip<AgentEvent>("GET__events", "eventVariants.agent.approval")
        assertEquals(AgentEvent.PENDING, asked.state)
        val answered = roundTrip<AgentEvent>("GET__events", "eventVariants.agent.approval answered")
        assertEquals(AgentEvent.ACCEPTED, answered.state)
        assertEquals(asked.approval!!.id, answered.approval!!.id)
        assertTrue("an answered frame comes after the one that asked", answered.seq > asked.seq)
        val reset = roundTrip<AgentEvent>("GET__events", "eventVariants.agent.reset")
        assertEquals(AgentEvent.RESET, reset.kind)
        assertTrue("a reset names the transcript that replaced the old one", reset.epoch != item.epoch)
        assertEquals(false, reset.turnActive)
        assertNotNull(reset.state)
    }

    /** Frames the Mac had to drop for a phone that fell behind are said, not hidden. */
    @Test
    fun `a resync says how many frames were dropped`() {
        assertEquals(7, roundTrip<ResyncEvent>("GET__events", "events.resync").dropped)
    }

    /**
     * The refusals a status can carry beyond the one in `errors`, each strictly: every one
     * decodes, maps to the case a screen can act on, and the set is pinned, so a new one
     * fails here rather than reaching a person as a number.
     */
    @Test
    fun `every error variant decodes and maps to the case a screen acts on`() {
        val seen = mutableSetOf<String>()
        for (name in EXPECTED_FIXTURES.sorted()) {
            val variants = fixture(name)["errorVariants"] ?: continue
            assertTrue("$name: errorVariants is {status: {label: {error}}}", variants is JsonObject)
            for ((status, labels) in variants as JsonObject) {
                val code = status.toIntOrNull()
                assertNotNull("$name: $status is not a status", code)
                assertTrue("$name $status: labels are an object", labels is JsonObject)
                for ((label, body) in labels as JsonObject) {
                    assertTrue("$name $status $label: a body is {error}", body is JsonObject && body.keys == setOf("error"))
                    val decoded = json.decodeFromString<ErrorResponse>(body.toString())
                    assertTrue("$name $status $label says nothing", decoded.error.isNotBlank())
                    val mapped = TransportError.from(code!!, body.toString(), "/x")
                    assertNotNull(mapped)
                    assertTrue("$name $status $label falls through to Server", mapped !is TransportError.Server)
                    assertEquals("$name $status $label reaches a person in the Mac's words", decoded.error, mapped!!.message)
                    seen += "$name $status $label"
                }
            }
        }
        assertEquals(
            "The Mac documents different refusals now — refresh, map them, then list them here",
            EXPECTED_ERROR_VARIANTS, seen,
        )
        // The ones the Agents tab acts on, by case.
        val approvals = "POST__agent_sessions__engine__approvals__id_"
        for (label in listOf("still screening", "engine stopped")) {
            assertTrue(TransportError.from(409, part(approvals, "errorVariants.409.$label").toString(), "/x") is TransportError.Conflict)
        }
        assertTrue(
            TransportError.from(409, part("POST__agent_sessions__engine__messages", "errorVariants.409.turn in progress").toString(), "/x")
                is TransportError.Conflict,
        )
        assertTrue(
            TransportError.from(403, part("GET__agent_sessions", "errorVariants.403.swarm").toString(), "/x")
                is TransportError.Forbidden,
        )
    }

    /** Every refusal an agent route documents reaches a screen as a case it can act on. */
    @Test
    fun `the agent routes' refusals map to what a screen can do about them`() {
        val approvals = "POST__agent_sessions__engine__approvals__id_"
        assertTrue(TransportError.from(403, part(approvals, "errors.403").toString(), "/x") is TransportError.Forbidden)
        assertTrue(TransportError.from(409, part(approvals, "errors.409").toString(), "/x") is TransportError.Conflict)
        assertTrue(
            TransportError.from(409, part(approvals, "errors.409").toString(), "/x")!!.message!!
                .contains("answered at the Mac"),
        )
        assertTrue(TransportError.from(400, part(approvals, "errors.400").toString(), "/x") is TransportError.BadRequest)
        for (name in listOf("GET__agent_sessions", "GET__agent_sessions__engine_", approvals)) {
            assertEquals(listOf("full"), fixture(name)["scopes"].toString()
                .removeSurrounding("[", "]").split(",").map { it.trim().removeSurrounding("\"") })
        }
    }

    // MARK: - The export itself

    companion object {
        /**
         * Every `errorVariants` entry the export carries, as "fixture status label". Pinned
         * like the fixtures, and for the same reason: a refusal the Mac grows fails here.
         */
        val EXPECTED_ERROR_VARIANTS = setOf(
            "DELETE__agent_sessions__engine_ 403 swarm",
            "GET__agent_sessions 403 swarm",
            "GET__agent_sessions__engine_ 403 swarm",
            "POST__agent_sessions__engine__approvals__id_ 403 swarm",
            "POST__agent_sessions__engine__approvals__id_ 409 engine stopped",
            "POST__agent_sessions__engine__approvals__id_ 409 still screening",
            "POST__agent_sessions__engine__interrupt 403 swarm",
            "POST__agent_sessions__engine__messages 403 swarm",
            "POST__agent_sessions__engine__messages 409 turn in progress",
            "POST__agent_sessions__engine__new 403 swarm",
            "POST__agent_sessions__engine__start 403 swarm",
            "POST__agent_sessions__engine__start 409 stopping",
            "DELETE__ondevice_models__id_ 403 swarm",
            "GET__ondevice_models 403 swarm",
            "GET__ondevice_models__id__file 403 swarm",
            "POST__ondevice_models__id__prepare 403 swarm",
        )

        /**
         * The contract is a copy of something generated elsewhere, and a copy goes
         * stale quietly. This is the list that makes it loud: when it changes,
         * `contract/refresh.sh` is the fix — not this list.
         */
        val EXPECTED_FIXTURES = setOf(
            // Two routes the Mac grew so that tests and CLIs can pair at all:
            // pairing codes used to be mintable only from its own Settings window.
            // They are loopback-and-control-token only, which means no device can
            // ever reach them — this app included, whatever it is holding. Listed
            // because the export is the whole export; deliberately not mirrored,
            // because a type for a route this app is forbidden to call would be a
            // type nothing can ever use.
            //
            // The Jev and recommend routes below are unmirrored for the softer
            // reason: nothing in this app speaks them yet. `GET /jev` left that list
            // in M3 — the Create tab reads it to know whether this Mac routes media
            // itself — but the calibration, guardrail and recommend shapes are still
            // types nothing would call, and a type nothing calls is a guess that rots.
            "DELETE__agent_sessions__engine_",
            "DELETE__buddy_devices__id_",
            "DELETE__buddy_invitations",
            // M5: the models the Mac keeps for this phone, mirrored in `OnDeviceApi.kt`.
            "DELETE__ondevice_models__id_",
            "GET__ondevice_models",
            "GET__ondevice_models__id__file",
            "POST__ondevice_models__id__prepare",
            "GET__agent_sessions",
            "GET__agent_sessions__engine_",
            "GET__buddy_devices",
            "GET__catalog",
            "GET__conversations",
            "GET__conversations__id_",
            "GET__events",
            "GET__health",
            "GET__image_models",
            "GET__installed",
            "GET__jev",
            "GET__jev_calibration",
            "GET__jev_guardrails_recent",
            "GET__mesh_models",
            "GET__metrics",
            "GET__profile",
            "GET__recommend",
            "GET__status",
            "GET__media__id_",
            "GET__swarm",
            "GET__swarm_peers__name__status",
            "GET__v1_node",
            "GET__video_models",
            "GET__video_queue",
            "POST__agent_sessions__engine__approvals__id_",
            "POST__agent_sessions__engine__interrupt",
            "POST__agent_sessions__engine__messages",
            "POST__agent_sessions__engine__new",
            "POST__agent_sessions__engine__start",
            "POST__benchmark",
            "POST__buddy_invitations",
            "POST__buddy_pair",
            "POST__chat",
            "POST__chat_stream",
            "POST__conversations",
            "POST__conversations__id__messages",
            "POST__decide",
            "POST__image_generate",
            "POST__image_plan",
            "POST__install",
            "POST__jev",
            "POST__jev_calibrate",
            "POST__load",
            "POST__mesh_generate",
            "POST__mesh_plan",
            "POST__plan",
            "POST__recommend",
            "POST__unload",
            "POST__uploads",
            "POST__v1_systemone",
            "POST__video_generate",
            "POST__video_queue",
            "POST__video_queue_control"
        )
    }

    @Test
    fun `the contract is the whole export and nothing else`() {
        val directory = File(javaClass.classLoader!!.getResource("GET__health.json")!!.toURI())
            .parentFile
        val fixtures = directory.listFiles { file -> file.extension == "json" }!!
            .map { it.nameWithoutExtension }.toSet()
        val missing = (EXPECTED_FIXTURES - fixtures).sorted()
        val extra = (fixtures - EXPECTED_FIXTURES).sorted()
        assertTrue("The contract is missing $missing — run contract/refresh.sh", missing.isEmpty())
        assertTrue("The Mac grew $extra — mirror them, then add them here", extra.isEmpty())
        assertTrue(
            "routes.md comes with the export",
            File(directory, "routes.md").exists(),
        )
    }

    /**
     * Every status any route documents has a case of its own. A new one falling into
     * `Server` would reach a person as a number.
     */
    @Test
    fun `every documented status is mapped`() {
        val seen = mutableSetOf<Int>()
        for (name in EXPECTED_FIXTURES.sorted()) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            for ((status, body) in errors) {
                val code = status.toInt()
                seen.add(code)
                val mapped = TransportError.from(code, body.toString(), "/x")
                assertNotNull("$name documents $code; nothing maps it", mapped)
                assertTrue(
                    // A 500 is a server error and `Server` is what it is; what matters
                    // is that it arrives as the Mac's own sentence rather than as a
                    // number, which the next assertion checks. Everything else has to
                    // have a case of its own.
                    "$name documents $code and it falls through to Server",
                    mapped !is TransportError.Server || code == 500,
                )
                assertTrue(
                    "$name $code reaches a person as nothing",
                    !mapped!!.message.isNullOrBlank(),
                )
            }
        }
        assertEquals(
            "The statuses the Mac documents changed — run contract/refresh.sh, then map them",
            // 503 and 507 arrived with the phone's models: the Mac's library drive is gone,
            // and the Mac has no room.
            setOf(400, 401, 403, 404, 409, 411, 413, 415, 416, 429, 500, 503, 507),
            seen,
        )
    }

    /**
     * Three things the current export says that an older copy did not. A stale
     * contract/ fails here rather than being discovered on a phone.
     */
    @Test
    fun `the export is the current one`() {
        for (name in EXPECTED_FIXTURES.filter { it.startsWith("POST__") }) {
            // The POSTs that take no body at all, and so have no 400 to give — three from
            // before, and the three agent verbs, whose fixtures say `"request": null`.
            if (name in setOf(
                    "POST__benchmark", "POST__unload", "POST__jev_calibrate",
                    "POST__agent_sessions__engine__start", "POST__agent_sessions__engine__new",
                    "POST__agent_sessions__engine__interrupt",
                )
            ) {
                assertEquals("$name takes no body", JsonNull, fixture(name)["request"])
                continue
            }
            val errors = fixture(name)["errors"] as? JsonObject
            assertNotNull("$name documents no errors at all", errors)
            assertNotNull("$name should document a 400 — refresh the contract", errors!!["400"])
        }
        for (name in listOf("GET__recommend", "GET__conversations__id_", "DELETE__buddy_devices__id_")) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            assertNotNull("$name should document a 404 — refresh the contract", errors["404"])
        }
        for (name in listOf("POST__chat_stream", "POST__conversations__id__messages", "GET__events")) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            assertNotNull("$name should document a 429 — refresh the contract", errors["429"])
        }
    }

    // MARK: - Errors

    @Test
    fun `every error body in the contract decodes and maps`() {
        val directory = File(javaClass.classLoader!!.getResource("GET__health.json")!!.toURI())
            .parentFile
        var checked = 0
        directory.listFiles { file -> file.extension == "json" }!!.forEach { file ->
            val fields = Json.parseToJsonElement(file.readText()) as JsonObject
            val errors = fields["errors"] as? JsonObject ?: return@forEach
            for ((status, body) in errors) {
                val decoded = json.decodeFromString<ErrorResponse>(body.toString())
                assertTrue("${file.name} $status has an empty message", decoded.error.isNotEmpty())
                assertNotNull(
                    "$status should map to an error",
                    TransportError.from(status.toInt(), body.toString(), "/x"),
                )
                checked++
            }
        }
        assertTrue("Every route lists the errors it can answer", checked > 30)
    }

    @Test
    fun `the scope refusal is not an unpairing`() {
        val body = part("POST__load", "errors.403").toString()
        val error = TransportError.from(403, body, "/load")
        assertTrue(error is TransportError.Forbidden)
        assertTrue(error!!.message!!.contains("chat only"))
    }

    @Test
    fun `a conversation conflict is its own case`() {
        val body = part("POST__conversations__id__messages", "errors.409").toString()
        assertTrue(
            TransportError.from(409, body, "/conversations/1/messages")
                is TransportError.Conflict,
        )
    }

    @Test
    fun `the body limit the Mac states is the one this app enforces`() {
        val body = part("POST__chat", "errors.413").toString()
        val error = TransportError.from(413, body, "/chat")
        assertTrue(error is TransportError.TooLarge)
        // The Mac says 4194304 bytes; the app refuses before sending that much.
        assertTrue(error!!.message!!.contains("4194304"))
        assertEquals(4 * 1024 * 1024, SendLimits.MAX_BODY_BYTES)
    }

    // MARK: - Requests this app builds

    @Test
    fun `requests encode the way the Mac reads them`() {
        val fields = Json.parseToJsonElement(
            json.encodeToString(LoadRequest("bonsai-2-27b", "PTQ1_0")),
        ) as JsonObject
        assertEquals("bonsai-2-27b", (fields["modelID"] as JsonPrimitive).content)
        assertNull("Absent options must not be sent as null", fields["contextLength"])
    }

    @Test
    fun `a new message carries content, not a transcript`() {
        val request = NewMessageRequest(
            content = "What is this?",
            images = listOf("data:image/jpeg;base64,AAA"),
            maxTokens = 2048,
        )
        val fields = Json.parseToJsonElement(json.encodeToString(request)) as JsonObject
        assertEquals("What is this?", (fields["content"] as JsonPrimitive).content)
        assertEquals(1, (fields["images"] as JsonArray).size)
        assertEquals("2048", (fields["maxTokens"] as JsonPrimitive).content)
        assertNull("The Mac has the history; this route takes one message", fields["messages"])
    }

    @Test
    fun `an empty image list is still sent`() {
        val request = ChatRequest(listOf(ChatMessageWire("user", "hi")))
        val message = ((Json.parseToJsonElement(json.encodeToString(request)) as JsonObject)
            .getValue("messages") as JsonArray)[0] as JsonObject
        assertEquals(0, (message["images"] as JsonArray).size)
    }

    // MARK: - A failed load

    /** Every ending the Mac documents on `GET /status`, decoded and re-encoded whole. */
    @Test fun everyFailedLoadTheMacDocumentsRoundTrips() {
        val variants = (fixture("GET__status")["responseVariants"] as JsonObject).keys
        val decoded = variants.associateWith { roundTrip<Status>("GET__status", "responseVariants.$it") }
        assertTrue("the export documents the endings", decoded.size >= 5)
        decoded.values.forEach { status ->
            val failure = assertNotNullAnd(status.failure)
            assertFalse("state stays one line", status.state.contains('\n'))
            assertNull(status.loadedModelID)
            assertTrue(failure.at.isNotBlank())
        }

        val killed = decoded.getValue("after a failed load").failure!!
        assertEquals(LoadFailure.Reason.Killed, killed.kind)
        assertEquals(9, killed.signal)
        assertTrue("the log is the detail, not the sentence", killed.detail!!.contains("load_tensors"))
        assertEquals("llama.cpp · signal 9", killed.facts)

        val replaced = decoded.getValue("after a load that was replaced").failure!!
        assertTrue(replaced.wasReplaced)
        assertEquals(LoadFailure.Reason.Replaced, replaced.kind)
        assertEquals(LoadFailure.Reason.Cancelled, decoded.getValue("after a load that was cancelled").failure!!.kind)
        assertEquals(LoadFailure.Reason.TimedOut, decoded.getValue("after a load that never answered").failure!!.kind)

        // A device paired for chat is told the same failure without the runtime's log.
        val withheld = decoded.getValue("as a chat-scope device or a peer sees it")
        assertNull(withheld.failure!!.detail)
        assertEquals(decoded.getValue("after a failed load").state, withheld.state)
    }

    @Test
    fun `a failure reason this app does not know reads as exited`() {
        val status = json.decodeFromString<Status>(
            """{"state":"The runtime ran out of cheese.","expertStreaming":false,
               "failure":{"reason":"outOfCheese","wasReplaced":false,"at":"2026-09-19T11:04:38Z"}}""",
        )
        assertEquals(LoadFailure.Reason.Exited, status.failure!!.kind)
        assertNull(status.failure!!.detail)
        assertNull("nothing to say about how it ended", status.failure!!.facts)
    }

    private fun <T : Any> assertNotNullAnd(value: T?): T {
        assertNotNull(value)
        return value!!
    }

    // MARK: - Forgiving where the Mac says it may be

    @Test
    fun `a status from an older Mac still decodes`() {
        val status = json.decodeFromString<Status>("""{"state":"Not loaded","expertStreaming":false}""")
        assertFalse(status.hasLoadedModel)
        assertNull("a Mac from before failures were structured sends none", status.failure)
    }

    @Test
    fun `a pair response without a scope means full`() {
        val paired = json.decodeFromString<PairResponse>(
            """{"deviceID":"1","token":"t","macName":"Mac","port":8788}""",
        )
        assertNull(paired.scope)
        assertEquals(DeviceScope.Full, DeviceScope.from(paired.scope))
    }
}
