package dev.siliconoptimizer.buddy

import dev.siliconoptimizer.buddy.chat.SendLimits
import dev.siliconoptimizer.buddy.transport.CatalogModel
import dev.siliconoptimizer.buddy.transport.ChatMessageWire
import dev.siliconoptimizer.buddy.transport.ChatMetrics
import dev.siliconoptimizer.buddy.transport.ChatRequest
import dev.siliconoptimizer.buddy.transport.ChatResponse
import dev.siliconoptimizer.buddy.transport.ConversationDetail
import dev.siliconoptimizer.buddy.transport.ConversationSummary
import dev.siliconoptimizer.buddy.transport.DeviceScope
import dev.siliconoptimizer.buddy.transport.DownloadProgress
import dev.siliconoptimizer.buddy.transport.ErrorResponse
import dev.siliconoptimizer.buddy.transport.Health
import dev.siliconoptimizer.buddy.transport.Heartbeat
import dev.siliconoptimizer.buddy.transport.ImageModel
import dev.siliconoptimizer.buddy.transport.InstalledModel
import dev.siliconoptimizer.buddy.transport.JobProgress
import dev.siliconoptimizer.buddy.transport.LoadRequest
import dev.siliconoptimizer.buddy.transport.MeshModel
import dev.siliconoptimizer.buddy.transport.Metrics
import dev.siliconoptimizer.buddy.transport.NewConversation
import dev.siliconoptimizer.buddy.transport.NewMessageRequest
import dev.siliconoptimizer.buddy.transport.NodeAdvertisement
import dev.siliconoptimizer.buddy.transport.PairRequest
import dev.siliconoptimizer.buddy.transport.PairResponse
import dev.siliconoptimizer.buddy.transport.PairedDevice
import dev.siliconoptimizer.buddy.transport.Plan
import dev.siliconoptimizer.buddy.transport.PlanRequest
import dev.siliconoptimizer.buddy.transport.Profile
import dev.siliconoptimizer.buddy.transport.Status
import dev.siliconoptimizer.buddy.transport.StatusMessage
import dev.siliconoptimizer.buddy.transport.SwarmView
import dev.siliconoptimizer.buddy.transport.TokenEvent
import dev.siliconoptimizer.buddy.transport.TransportError
import dev.siliconoptimizer.buddy.transport.VideoModel
import dev.siliconoptimizer.buddy.transport.VideoQueueView
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.doubleOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The mirrored types, checked against the Mac's own export.
 *
 * `contract/` is generated by silicon-optimizer's ContractExportTests — the shapes its
 * wire types actually encode. Each file holds a route: its request, its response, the
 * events it can send and the errors it can answer. The round trip is the part that
 * matters: decode, re-encode, compare the JSON. A field this app forgot to mirror
 * disappears in the re-encode, so the comparison fails.
 */
class ContractTest {

    private val json = Json {
        ignoreUnknownKeys = true
        explicitNulls = false
        encodeDefaults = true
    }

    private fun fixture(name: String): JsonObject {
        val text = javaClass.classLoader?.getResourceAsStream("$name.json")?.bufferedReader()
            ?.readText() ?: error("Missing fixture $name.json — run contract/refresh.sh")
        return Json.parseToJsonElement(text) as JsonObject
    }

    private fun part(name: String, part: String): JsonElement {
        val fields = fixture(name)
        return when {
            part.startsWith("events.") ->
                (fields["events"] as JsonObject).getValue(part.removePrefix("events."))
            part.startsWith("errors.") ->
                (fields["errors"] as JsonObject).getValue(part.removePrefix("errors."))
            else -> fields.getValue(part)
        }
    }

    private inline fun <reified T> roundTrip(name: String, part: String = "response"): T {
        val piece = part(name, part)
        val decoded = json.decodeFromString<T>(piece.toString())
        val reencoded = json.encodeToString(decoded)
        assertEquals(
            "$name.$part changed shape on a round trip",
            decoded,
            json.decodeFromString<T>(reencoded),
        )
        val differences = difference(strip(piece), strip(Json.parseToJsonElement(reencoded)))
        assertTrue(
            "$name.$part lost or changed fields on a round trip:\n" +
                differences.joinToString("\n"),
            differences.isEmpty(),
        )
        return decoded
    }

    private fun strip(element: JsonElement): JsonElement = when (element) {
        is JsonObject -> JsonObject(
            element.filterValues { it !is JsonNull }.mapValues { strip(it.value) },
        )
        is JsonArray -> JsonArray(element.map { strip(it) })
        else -> element
    }

    private fun difference(mine: JsonElement, theirs: JsonElement, path: String = ""): List<String> =
        when {
            mine is JsonObject && theirs is JsonObject ->
                (mine.keys + theirs.keys).sorted().flatMap { key ->
                    val childPath = if (path.isEmpty()) key else "$path.$key"
                    val a = mine[key]
                    val b = theirs[key]
                    when {
                        a == null -> listOf("+ $childPath appeared after the round trip")
                        b == null -> listOf("- $childPath was lost — is it mirrored?")
                        else -> difference(a, b, childPath)
                    }
                }
            mine is JsonArray && theirs is JsonArray ->
                if (mine.size != theirs.size) {
                    listOf("$path has ${mine.size} items, round trip has ${theirs.size}")
                } else {
                    mine.indices.flatMap { difference(mine[it], theirs[it], "$path[$it]") }
                }
            mine is JsonPrimitive && theirs is JsonPrimitive -> {
                val a = mine.doubleOrNull
                val b = theirs.doubleOrNull
                val same = if (a != null && b != null) a == b else mine.content == theirs.content
                if (same) emptyList() else listOf("$path: $mine != $theirs")
            }
            else -> if (mine == theirs) emptyList() else listOf("$path: $mine != $theirs")
        }

    // MARK: - The routes this app calls today

    @Test fun health() { assertEquals("ok", roundTrip<Health>("GET__health").status) }

    @Test fun status() { assertTrue(roundTrip<Status>("GET__status").hasLoadedModel) }

    @Test fun profile() { assertTrue(roundTrip<Profile>("GET__profile").totalMemoryBytes > 0) }

    @Test fun metrics() { assertTrue(roundTrip<Metrics>("GET__metrics").memoryTotalBytes > 0) }

    @Test fun installed() {
        assertTrue(roundTrip<List<InstalledModel>>("GET__installed").isNotEmpty())
    }

    @Test fun catalog() {
        assertTrue(roundTrip<List<CatalogModel>>("GET__catalog").any { it.recommendation != null })
    }

    @Test fun recommend() { roundTrip<CatalogModel>("GET__recommend") }

    @Test fun swarm() { roundTrip<SwarmView>("GET__swarm") }

    @Test fun nodeAdvertisement() {
        assertTrue(roundTrip<NodeAdvertisement>("GET__v1_node").profile.memoryGB > 0)
    }

    @Test fun videoModels() { roundTrip<List<VideoModel>>("GET__video_models") }

    @Test fun videoQueue() { roundTrip<VideoQueueView>("GET__video_queue") }

    @Test fun imageModels() { roundTrip<List<ImageModel>>("GET__image_models") }

    @Test fun meshModels() { roundTrip<List<MeshModel>>("GET__mesh_models") }

    @Test fun chat() {
        roundTrip<ChatRequest>("POST__chat", "request")
        assertTrue(roundTrip<ChatResponse>("POST__chat").content.isNotEmpty())
    }

    @Test fun loadAndInstall() {
        roundTrip<LoadRequest>("POST__load", "request")
        roundTrip<Status>("POST__load")
        roundTrip<LoadRequest>("POST__install", "request")
        roundTrip<StatusMessage>("POST__install")
        roundTrip<StatusMessage>("POST__unload")
    }

    @Test fun plan() {
        roundTrip<PlanRequest>("POST__plan", "request")
        roundTrip<Plan>("POST__plan")
    }

    // MARK: - The M0 routes

    @Test fun pairing() {
        roundTrip<PairRequest>("POST__buddy_pair", "request")
        val paired = roundTrip<PairResponse>("POST__buddy_pair")
        assertEquals(DeviceScope.Full, DeviceScope.from(paired.scope))
    }

    @Test fun pairedDevices() {
        assertEquals("full", roundTrip<List<PairedDevice>>("GET__buddy_devices").first().scope)
        roundTrip<StatusMessage>("DELETE__buddy_devices__id_")
    }

    @Test fun conversations() {
        assertEquals(2, roundTrip<List<ConversationSummary>>("GET__conversations").first().messageCount)
        roundTrip<NewConversation>("POST__conversations", "request")
        roundTrip<ConversationSummary>("POST__conversations")
    }

    @Test fun conversationDetail() {
        val detail = roundTrip<ConversationDetail>("GET__conversations__id_")
        assertFalse(detail.isGenerating)
        assertEquals(2, detail.messages.size)
    }

    /** The route this app got wrong once: it takes one message, not a transcript. */
    @Test fun sendingAMessageToAConversation() {
        val request = roundTrip<NewMessageRequest>("POST__conversations__id__messages", "request")
        assertTrue(request.content.isNotEmpty())
        assertEquals(emptyList<String>(), request.images)
    }

    @Test fun chatStreamEvents() {
        roundTrip<TokenEvent>("POST__chat_stream", "events.token")
        roundTrip<TokenEvent>("POST__chat_stream", "events.reasoning")
        assertNotNull(roundTrip<ChatMetrics>("POST__chat_stream", "events.finished").timeToFirstToken)
        roundTrip<ErrorResponse>("POST__chat_stream", "events.error")
    }

    @Test fun serverEvents() {
        roundTrip<Status>("GET__events", "events.status")
        assertEquals(0.42, roundTrip<DownloadProgress>("GET__events", "events.download").progress)
        assertEquals("running", roundTrip<JobProgress>("GET__events", "events.job").status)
        roundTrip<Heartbeat>("GET__events", "events.heartbeat")
    }


    // MARK: - The export itself

    companion object {
        /**
         * The contract is a copy of something generated elsewhere, and a copy goes
         * stale quietly. This is the list that makes it loud: when it changes,
         * `contract/refresh.sh` is the fix — not this list.
         */
        val EXPECTED_FIXTURES = setOf(
            // The last six are routes the Mac grew for Jev's own settings, its
            // calibration, the guardrail's recent screenings and the task-shaped
            // `POST /recommend`. Listed so the export is accounted for; no type
            // here mirrors them yet, because nothing in this app speaks them —
            // the Jev settings are the Mac's own business and the pages that
            // would use the other two arrive in M3. Mirroring a type nothing
            // calls is a guess that rots.
            "DELETE__buddy_devices__id_",
            "GET__buddy_devices",
            "GET__catalog",
            "GET__conversations",
            "GET__conversations__id_",
            "GET__events",
            "GET__health",
            "GET__image_models",
            "GET__installed",
            "GET__jev",
            "GET__jev_calibration",
            "GET__jev_guardrails_recent",
            "GET__mesh_models",
            "GET__metrics",
            "GET__profile",
            "GET__recommend",
            "GET__status",
            "GET__swarm",
            "GET__v1_node",
            "GET__video_models",
            "GET__video_queue",
            "POST__benchmark",
            "POST__buddy_pair",
            "POST__chat",
            "POST__chat_stream",
            "POST__conversations",
            "POST__conversations__id__messages",
            "POST__decide",
            "POST__image_generate",
            "POST__image_plan",
            "POST__install",
            "POST__jev",
            "POST__jev_calibrate",
            "POST__load",
            "POST__mesh_generate",
            "POST__mesh_plan",
            "POST__plan",
            "POST__recommend",
            "POST__unload",
            "POST__v1_systemone",
            "POST__video_generate",
            "POST__video_queue",
            "POST__video_queue_control"
        )
    }

    @Test
    fun `the contract is the whole export and nothing else`() {
        val directory = File(javaClass.classLoader!!.getResource("GET__health.json")!!.toURI())
            .parentFile
        val fixtures = directory.listFiles { file -> file.extension == "json" }!!
            .map { it.nameWithoutExtension }.toSet()
        val missing = (EXPECTED_FIXTURES - fixtures).sorted()
        val extra = (fixtures - EXPECTED_FIXTURES).sorted()
        assertTrue("The contract is missing $missing — run contract/refresh.sh", missing.isEmpty())
        assertTrue("The Mac grew $extra — mirror them, then add them here", extra.isEmpty())
        assertTrue(
            "routes.md comes with the export",
            File(directory, "routes.md").exists(),
        )
    }

    /**
     * Every status any route documents has a case of its own. A new one falling into
     * `Server` would reach a person as a number.
     */
    @Test
    fun `every documented status is mapped`() {
        val seen = mutableSetOf<Int>()
        for (name in EXPECTED_FIXTURES.sorted()) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            for ((status, body) in errors) {
                val code = status.toInt()
                seen.add(code)
                val mapped = TransportError.from(code, body.toString(), "/x")
                assertNotNull("$name documents $code; nothing maps it", mapped)
                assertTrue(
                    "$name documents $code and it falls through to Server",
                    mapped !is TransportError.Server,
                )
                assertTrue(
                    "$name $code reaches a person as nothing",
                    !mapped!!.message.isNullOrBlank(),
                )
            }
        }
        assertEquals(
            "The statuses the Mac documents changed — run contract/refresh.sh, then map them",
            setOf(400, 401, 403, 404, 409, 411, 413, 429),
            seen,
        )
    }

    /**
     * Three things the current export says that an older copy did not. A stale
     * contract/ fails here rather than being discovered on a phone.
     */
    @Test
    fun `the export is the current one`() {
        for (name in EXPECTED_FIXTURES.filter { it.startsWith("POST__") }) {
            // The three POSTs that take no body at all, and so have no 400 to give.
            if (name in setOf("POST__benchmark", "POST__unload", "POST__jev_calibrate")) continue
            val errors = fixture(name)["errors"] as? JsonObject
            assertNotNull("$name documents no errors at all", errors)
            assertNotNull("$name should document a 400 — refresh the contract", errors!!["400"])
        }
        for (name in listOf("GET__recommend", "GET__conversations__id_", "DELETE__buddy_devices__id_")) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            assertNotNull("$name should document a 404 — refresh the contract", errors["404"])
        }
        for (name in listOf("POST__chat_stream", "POST__conversations__id__messages", "GET__events")) {
            val errors = fixture(name)["errors"] as? JsonObject ?: continue
            assertNotNull("$name should document a 429 — refresh the contract", errors["429"])
        }
    }

    // MARK: - Errors

    @Test
    fun `every error body in the contract decodes and maps`() {
        val directory = File(javaClass.classLoader!!.getResource("GET__health.json")!!.toURI())
            .parentFile
        var checked = 0
        directory.listFiles { file -> file.extension == "json" }!!.forEach { file ->
            val fields = Json.parseToJsonElement(file.readText()) as JsonObject
            val errors = fields["errors"] as? JsonObject ?: return@forEach
            for ((status, body) in errors) {
                val decoded = json.decodeFromString<ErrorResponse>(body.toString())
                assertTrue("${file.name} $status has an empty message", decoded.error.isNotEmpty())
                assertNotNull(
                    "$status should map to an error",
                    TransportError.from(status.toInt(), body.toString(), "/x"),
                )
                checked++
            }
        }
        assertTrue("Every route lists the errors it can answer", checked > 30)
    }

    @Test
    fun `the scope refusal is not an unpairing`() {
        val body = part("POST__load", "errors.403").toString()
        val error = TransportError.from(403, body, "/load")
        assertTrue(error is TransportError.Forbidden)
        assertTrue(error!!.message!!.contains("chat only"))
    }

    @Test
    fun `a conversation conflict is its own case`() {
        val body = part("POST__conversations__id__messages", "errors.409").toString()
        assertTrue(
            TransportError.from(409, body, "/conversations/1/messages")
                is TransportError.Conflict,
        )
    }

    @Test
    fun `the body limit the Mac states is the one this app enforces`() {
        val body = part("POST__chat", "errors.413").toString()
        val error = TransportError.from(413, body, "/chat")
        assertTrue(error is TransportError.TooLarge)
        // The Mac says 4194304 bytes; the app refuses before sending that much.
        assertTrue(error!!.message!!.contains("4194304"))
        assertEquals(4 * 1024 * 1024, SendLimits.MAX_BODY_BYTES)
    }

    // MARK: - Requests this app builds

    @Test
    fun `requests encode the way the Mac reads them`() {
        val fields = Json.parseToJsonElement(
            json.encodeToString(LoadRequest("bonsai-2-27b", "PTQ1_0")),
        ) as JsonObject
        assertEquals("bonsai-2-27b", (fields["modelID"] as JsonPrimitive).content)
        assertNull("Absent options must not be sent as null", fields["contextLength"])
    }

    @Test
    fun `a new message carries content, not a transcript`() {
        val request = NewMessageRequest(
            content = "What is this?",
            images = listOf("data:image/jpeg;base64,AAA"),
            maxTokens = 2048,
        )
        val fields = Json.parseToJsonElement(json.encodeToString(request)) as JsonObject
        assertEquals("What is this?", (fields["content"] as JsonPrimitive).content)
        assertEquals(1, (fields["images"] as JsonArray).size)
        assertEquals("2048", (fields["maxTokens"] as JsonPrimitive).content)
        assertNull("The Mac has the history; this route takes one message", fields["messages"])
    }

    @Test
    fun `an empty image list is still sent`() {
        val request = ChatRequest(listOf(ChatMessageWire("user", "hi")))
        val message = ((Json.parseToJsonElement(json.encodeToString(request)) as JsonObject)
            .getValue("messages") as JsonArray)[0] as JsonObject
        assertEquals(0, (message["images"] as JsonArray).size)
    }

    // MARK: - Forgiving where the Mac says it may be

    @Test
    fun `a status from an older Mac still decodes`() {
        assertFalse(
            json.decodeFromString<Status>("""{"state":"Not loaded","expertStreaming":false}""")
                .hasLoadedModel,
        )
    }

    @Test
    fun `a pair response without a scope means full`() {
        val paired = json.decodeFromString<PairResponse>(
            """{"deviceID":"1","token":"t","macName":"Mac","port":8788}""",
        )
        assertNull(paired.scope)
        assertEquals(DeviceScope.Full, DeviceScope.from(paired.scope))
    }
}
